### ISSUE TITLE
bspwm issue in arch

### ISSUE THREAD

**Issue by mht130** [baskerville/bspwm#1000]
I installed bspwm just like how arch wiki and bspwm wiki had said but it's not working
after pressing Enter in sddm ,screen goes freeze(though the curser still working)

**Comment by dubcusb** [comment]
Are you sure the screen is actually frozen and it's not just an empty bspwm desktop? Do you have a configuration file (~/.config/bspwm/bspwmrc)?

**Comment by MarcinWieczorek** [comment]
I don't know if this issue is still relevant, if not - should be closed.
@mht130 post Xorg logs from `/var/log/`, make sure you have bspwmrc existing and executable, `$XDG_CONFIG_HOME` set properly. Try running it with startx (xinit) instead of sddm to narrow the problem.

**Comment by chris-aeviator** [comment]
I realized that since a year or so BSPWM seems to have issues on intel integrated graphics (X1 Carbon 6thG) on arch. Electron based apps as well as GPU enhanced tools like Alacritty do not play well with BSPWM.  After a while I will get the described applications to "tear" when swichting e.g. from Firefox to an Electron app. The image of the firefox window is kind of frozen onto the electron window, and only killing the electron window will release the space again. What's the smartest way of debugging this?
