### ISSUE TITLE
There is workspace called "Desktop" that behaves weird

### ISSUE THREAD

**Issue by fncamm** [baskerville/bspwm#1018]
I've just installed bspwm version 0.9.9 and when I execute this command 
```
bspc query -D --names
```

I see that there are 11 desktops, the first one is called `Desktop` and the rest are standart workspaces that has rome numbers as names.

When I press `super + 1` nothing really happens. When I press `super + 2` and check which workspace is active it says `I`, and when I press `super + 3` then it gets me to the second workspace.

I haven't done much changes in the configs but here they are 
[configs.zip](https://github.com/baskerville/bspwm/files/3666545/configs.zip)

**Comment by fncamm** [comment]
Well, it seems to be a feature but a bug. That workspace is added when there are more than 1 monitors connected. It's added automatically or after xrandr is used.

**Comment by mighty9245** [comment]
my rough guess: since monitor represents a list of it's desktops it can't be empty for some reason, so a new desktop is automatically added for each connected and configured monitor. i have no idea how to get rid of it (looks like this desktop can't even be deleted), but i know how to make keybindings work correctly: just remove the `^` sign before a number range, e. g.
```
super + {_, shift + }{1-5}
        bspc {desktop -f,node -d} {1-5}
```
