### ISSUE TITLE
after I ran dmenu , the terminal get the input focus but the cursor remains the not focused shape

### ISSUE THREAD

**Issue by jakio6** [baskerville/bspwm#1023]
after I ran dmenu , the terminal get the input focus but the cursor remains the not focused shape,, 
![image](https://user-images.githubusercontent.com/33382676/67450125-fdf3b500-f64e-11e9-862f-531c08bdba6c.png)

**Comment by dotnetfox** [comment]
It certainly is a bug, but it has no relation to bspwm since it affects other window managers and X11 graphic software as well.
Please read these pages to understand the situation:
https://github.com/i3/i3/issues/3528
https://git.suckless.org/dmenu/commit/db6093f6ec1bb884f7540f2512935b5254750b30.html
