### ISSUE TITLE
many desktops numbering and ordering

### ISSUE THREAD

**Issue by whoizit** [baskerville/bspwm#1040]
I want to have this configuration, how can i do this? (I can not achieve this)

On left monitor:
```
desktop|name
1|q
2|w
3|e
4|r
5|t
11|1
12|2
13|3
14|4
15|5
```
On right monitor:
```
desktop|name
6|y
7|u
8|i
9|o
10|p
16|6
17|7
18|8
19|9
20|0
```

**Comment by yad-tahir** [comment]
You can use the following command:

`bspc monitor <monitor-name>  -d <desktop1> <desktop2> <desktop3> ... `

Example:
`bspc monitor DP-1  -d 1 2 3 4 5`

If you are not sure about your monitor name, use 
`xrandr --listmonitors`

**Comment by whoizit** [comment]
I know how to do it. I can’t change the order of desktops.

**Comment by yad-tahir** [comment]
You can use always use desktop names instead of IDs. Example

`bspc desktop -f q instead of bspc desktop -f ^1`

Having said that, I think this hack can do it: Add desktops '1|q 2|w 3|e 4|r 5|t' to your first monitor and '6|y 7|u 8|i 9|o' to the other monitor. Then, add the rest to each monitor. I am not sure whether 'monitor -d' will re-index the list or not. I cannot test it with my current setup :cry:

**Comment by whoizit** [comment]
useful advice, but I'm afraid I returned to i3 and set it up in 5 minutes as I wanted. And I don’t want to come back yet. Bsp is too complex and poorly documented in my opinion.

**Comment by yad-tahir** [comment]
As far as I recall, workspaces in i3 are dynamically created and destroyed based on their usage, and thus assigning a workspace to a particular monitor, permanently, is not an option.

In regards to the documentation, I agree. Perhaps, sending a PR to the maintainer would help a lot.
