### ISSUE TITLE
better window matching for rules

### ISSUE THREAD

**Issue by absolutelynothelix** [baskerville/bspwm#1078]
can we have some love for rules? currently we can match windows either by class name or by instance name. it would be amazing if we could also match them by at least role.

i know about `external_rules_command` but i think matching windows by rule is basic enough to be implemented on our own.

if you're wondering, i'm trying to write a rule for firefox's picture-in-picture window and probably the only thing that allows to identify it is it's role.

i know that most likely i won't get any reply on this, but... hope dies last

**Comment by emanuele6** [comment]
What is a the "role" of a window? What do you mean? @mighty9245

**Comment by mighty9245** [comment]
@emanuele6, `WM_ROLE` window property

**Comment by emanuele6** [comment]
@mighty9245, I've never heard of it, but most windows don't have it: I tried checking the `WM_ROLE` of an `urxvt` window (see screenshot) and of a `qutebrowser` window and they both didn't have it.

![wm_role_no_such_atom](https://user-images.githubusercontent.com/20175435/88481898-5a795d00-cf5e-11ea-84c6-e96d0ed54a31.png)

Since most window don't even have this I don't see the point of being able to match windows via this atom when using `bspc rule`. You can easily just check the output of `xprop -id "$1" WM_ROLE` in your `external_rules_command` script if you want to apply a rule based on that atom.

Are you sure this is even a standard atom? I can't find any reference to it online. Keep in mind that one can set any atom; e.g.:
```sh
xprop -id "$(pfw)" -format HELLO_WORLD 8s -set HELLO_WORLD 'hi there'
``` 
(set the focused window's `HELLO_WORLD` atom to `hi there`)

---------------------------------------

[pfw](https://github.com/wmutils/core.git)

**Comment by mighty9245** [comment]
oh, it's called `WM_WINDOW_ROLE`, my bad. i don't have much apps to test, but at least firefox, discord, atom and thunar have it.

**Comment by emanuele6** [comment]
> WM_WINDOW_ROLE

I tried checking it on `urxvt` and `qutebrowser` and they didn't have it. I also checked on `telegram-desktop` and `zathura` and it doesn't have it. I tried `polybar` and it doesn't have it.

That's basically all the GUI programs I use, none of them have it!
It clearly is not as used as `WM_CLASS` and `WM_NAME`, you can just `xprop -id "$1" WM_WINDOW_ROLE` in your external rules script if you want to make a rule based on that; as you would do with the other uncoventional atoms (e.g. `_PICOM_ROUNDED`).

**Comment by emanuele6** [comment]
I tried checking it on `krita` and it has it:
```
$ xprop -id "$(xdo id -Nkrita -nkrita | head -1)" WM_WINDOW_ROLE
WM_WINDOW_ROLE(STRING) = "MainWindow#1"
```

Most programs don't have it though; there is no point in allowing to set a rule based on this rare atom!

**Comment by absolutelynothelix** [comment]
i'm not using bspwm anymore, so i'm closing this to reduce the amount of open issues.
