### ISSUE TITLE
per-monitor *_monocle_padding

### ISSUE THREAD

**Issue by gipert** [baskerville/bspwm#1114]
I'm trying to set the `bottom_monocle_padding` property on a per-monitor basis, but the following command:
```
bspc config -m DP-1 bottom_monocle_padding -29
```
applies it to all my monitors. Is this intentional?

**Comment by emanuele6** [comment]
If you re read the `SETTINGS` section of the manual page, you can see that there various kinds of settings:
* Global Settings
* Monitor and Desktop Settings: `-m` and `-d` can be used with these rules
* Desktop Settings: `-d` can be used with these rules
* Node Settings:  `-n` can be used with these rules

`top_monocle_padding`, `right_monocle_padding`, `bottom_monocle_padding` and `left_monocle_padding` are global settings.

So, yes, it is "intentional".

**Comment by gipert** [comment]
I see, guess I'll live with it. Grazie for the detailed answer!

**Comment by opalmay** [comment]
Hi,
Wanted this too so I made it https://github.com/opalmay/bspwm/commit/2bd836ff0b43cfb9690a06fb4e3c7355ae7c41c2

**Comment by opalmay** [comment]
Wanted this too so I made it https://github.com/opalmay/bspwm/commit/2bd836ff0b43cfb9690a06fb4e3c7355ae7c41c2
