### ISSUE TITLE
getting window info of a removed node (just before being removed).

### ISSUE THREAD

**Issue by Liupold** [baskerville/bspwm#1152]
Is there any way in which I can query / subscribe to bspc event such that I can get it's info (eg: state) just prior to being removed.

**Comment by jallbrit** [comment]
You can subscribe to the `node_remove` event, which will tell you the removed node's `node_id`. However, I don't know what happens when attempting to query that removed node's id's properties. I'm assuming they're no longer available, but I have not tested.

I mean, by definition, when `bspwm` reports that a node has been removed, the node *should* be gone. It wouldn't necessarily make sense to keep properties of removed nodes so that you could query on them.

If you really want to query removed node's properties (such as the node's `state`), you could subscribe to `node_add` and `node_remove`, and:

1. Log every new node's properties to a file
2. When a node is removed, you can check your log for its properties (including the node's `state`), then (optionally) remove that node's properties from the log so the log file doesn't grow in size.

**Comment by Liupold** [comment]
used similar technique.
