### ISSUE TITLE
focus gets lost after taking screenshot via flameshot

### ISSUE THREAD

**Issue by amosbird** [baskerville/bspwm#1160]
https://github.com/lupoDharkael/flameshot/issues/784

**Comment by emanuele6** [comment]
> **To Reproduce**
In bspwm, open any tiled window, invoke flameshot, press esc, the tiled window doesn't get the focus back.

I'm using the same version you are using:
```shell
$ flameshot --version
Flameshot v0.6.0
Compiled with Qt 5.14.1
```

I have never used `flameshot` before.
Can you tell me how to invoke `flameshot` to reproduce this?
I tried `flameshot full --clipboard`, but I couldn't reproduce the problem with that.

**Comment by amosbird** [comment]
it's just `flameshot gui`.

**Comment by emanuele6** [comment]
> it's just flameshot gui.

I also tried that, it just closes immediately: [https://i.imgur.com/K4SOXn8.mp4](https://i.imgur.com/K4SOXn8.mp4) .

**Comment by SeerLite** [comment]
I can reproduce this! I'm not sure if it's the WM or flameshot though. I remember other programs doing something similar but never bothered to report this because I felt it was easy enough to re-focus by focusing something else.

@emanuele6 that's strange, seems like another issue.

**Comment by ortango** [comment]
an unmanaged window that gains focus will cause this behavior (no window will regain bspwm focus). i think that is probably what's going on here.

**Comment by SeerLite** [comment]
That makes sense. Is there a way for bspwm to handle that and regain focus?

**Comment by ortango** [comment]
for actually fixing the issues - it's over my head.

i tried flameshot out. it runs in the background and pops the capture widget when requested -`flameshot gui` will exit immediately. so, doing something like `flameshot gui; bspc node -f` will not work... `bspc node -f` will regain input focus though.

in its current state flameshot does not build with newest QT. trying to change from setFocus() to grabKeyboard/Mouse is more trouble then it is worth for me (i don't know if it will work out anyway). flameshot's uses of setFocus seems buggy anyway because you can change focus away from it while the capture widget is open.... it does not handle that situation correctly.

bspwm does see the unmap events for flameshot's widget though - maybe you can add a hack to bspwm there...

**Comment by emanuele6** [comment]
Can you still reproduce this issue? It seems to be resolved.
