### ISSUE TITLE
chromium & brave & google-chrome browser popupwindows doesnt open

### ISSUE THREAD

**Issue by kristoferus75** [baskerville/bspwm#1174]
Hi !

on each of this browser types suddently right click menu doesnt open but if change focus to other workspace and then focus back the menus opens normaly again in the browser !

one trigger is if i open claws-mail (x2go session) immediantly the right click menu or bookmark folder diesnt open in the browser !

must be something with the fucus in bspwm  -> also if it doesnt work  and i open a second tiled app on same workspace menu in the browser open normaly again 

this config doesnt help
`bspc config ignore_ewmh_focus true`

with firefox i have no problems with this issue ...

thanks

kristoferus

**Comment by emanuele6** [comment]
This might be related to #811, but I'm not sure.

@instantepiphany, didn't you say you were working on solving this issue? Any updates?

**Comment by instantepiphany** [comment]
> This might be related to #811, but I'm not sure.
> 
> @instantepiphany, didn't you say that you were going to work on solving that issue? Any update?

@emanuele6 it sounds like it might be related. I've been working on it but I haven't worked with C in 6 years, and even then I wasn't very advanced. I'm also learning xlib and xcb, and the documentation is lacking in some areas, so I'm finding other existing code and reverse engineering that. 

I was also hoping for Baskerville to confirm I understood what he thought the problem was. At the moment I'm proceeding as if the problem is Electron windows needing a `LeaveNotify` event but not receiving it if the desktop is changed and the new desktop does not have a new window where the mouse pointer is.

But it may be that once I eventually get that change working, it doesn't fix the problem and it was a red herring.

I also am working fulltime at the moment so only working on this in my spare time. 

I'll update in #811 when I have something to add :)

**Comment by kristoferus75** [comment]
The problem looks like it was a dmenu problem
