### ISSUE TITLE
When focusing next/prev node more than one node is focused.

### ISSUE THREAD

**Issue by simonhughcom** [baskerville/bspwm#1182]
When calling 'bspc node -f next.local' or 'bspc node -f prev.local' more than one node get focused or sometimes all nodes in desktop get focused.

The problem occurs on my arch linux machine where bspwm version is at '0.9.10' but not my void linux machine where bspwm version is at '0.9.9'.

**Comment by rwilhelm** [comment]
Changes regarding this have been made here: https://github.com/baskerville/bspwm/commit/d87e6c0f773e189a3a62b2d066b982b3a4e2bd56

> `next` and `prev` might now return any node in the context of a depth-first in-order tree traversal.

Try `bspc node -f {next,prev}.local.!hidden.window` like in the since then updated [example sxhkdrc](https://github.com/baskerville/bspwm/blob/master/examples/sxhkdrc#L67).

**Comment by simonhughcom** [comment]
Ok great, that worked although I'm not exactly sure why, what is the '!hidden.window' bit for?

**Comment by rwilhelm** [comment]
I'd guess as the changes in https://github.com/baskerville/bspwm/commit/d87e6c0f773e189a3a62b2d066b982b3a4e2bd56 change the terminology from `window` to `leaf`, so a window must be selected with `.window` and `!hidden` seems to mean "not hidden". Take a look here #1113 for some reasoning.

**Comment by simonhughcom** [comment]
Cool, thanks for your help, I'm going to close the issue now.
