### ISSUE TITLE
Source files in bspwmrc

### ISSUE THREAD

**Issue by antiold** [baskerville/bspwm#1188]
When I try:
```
source rename_monitors # bspc monitor_name new_name
bspc ....
```
I get:
```
bspc: command not found in rename_monitors
```

**Comment by emanuele6** [comment]
I source files in `bspwmrc` and there is no problem (obviously!!!!).

Why are you so cryptic about this report? I can't help you if this is all you provide.

**Comment by antiold** [comment]
@emanuele6 This does not work for me:
```
# bspwmrc
source rename_monitors
bspc monitor A -d 1 2 3
```
```
#rename_monitors
bspc monitor -n A
```
bspwm defaults to normal config, I exit X and I get: `error in rename_monitors: bspc command not found`

**Comment by antiold** [comment]
This `trap` and `wait` do I need something like this?  https://github.com/desyncr/bspwmrc/blob/master/bspwmrc

**Comment by emanuele6** [comment]
> This trap and wait do I need something like this?  https://github.com/desyncr/bspwmrc/blob/master/bspwmrc

I don't know. Do you? That has nothing to do with `source`-ing files in a script, but if you want to use it, use it.
>     bspc monitor A -d 1 2 3

I have an hard time that your monitor is named "A"
>     bspc monitor  -n A

This command makes little sense since "A" is, supposedly, the monitor's name.

--------------------

Why are you wasting our time like this?
I told you that there is no problem with `source`-ing files in a `bspwmrc` file (written in `bash`, `zsh` or something else that supports **`source`**).
If it doesn't work for you, **YOU** are doing something wrong! If you don't post the problematic script, I can't tell you what is wrong with it!

If you want help, post your actual config or a script that allows me to reproduce your problem...
