### ISSUE TITLE
segfault when using % with non-existant desktops or monitors

### ISSUE THREAD

**Issue by ortango** [baskerville/bspwm#1196]
in cmd_node() dst in not initialized to null and cmd_node goes segfault when it hits transfer node after {monitor,desktop}_from_desc "succeeds".

this doesn't happen with cmd_query; setting dst to null for both `-m` and `-d` sections works around the problem, but i do not know if there are side effects.

    bspc node -m %doesntexist

i can provide a backtrace if needed.

**Comment by emanuele6** [comment]
> this doesn't happen with cmd_query; setting dst to null for both -m and -d sections works around the problem, but i do not know if there are side effects.

The most sensible way to fix this is probably setting loc->{desktop,monitor} to NULL in locate_{desktop,monitor} if the {desktop,monitor} is not found.
```diff
diff --git a/src/query.c b/src/query.c
index ba04458..46e6a03 100644
--- a/src/query.c
+++ b/src/query.c
@@ -951,6 +951,8 @@ bool locate_desktop(char *name, coordinates_t *loc)
 			}
 		}
 	}
+	loc->monitor = NULL;
+	loc->desktop = NULL;
 	return false;
 }
 
@@ -962,6 +964,7 @@ bool locate_monitor(char *name, coordinates_t *loc)
 			return true;
 		}
 	}
+	loc->monitor = NULL;
 	return false;
 }
 
```

**Comment by ortango** [comment]
out of curiosity is it wasteful to set set all three to null at initialization? or is there different problem with doing that?

**Comment by emanuele6** [comment]
> out of curiosity is it wasteful to set set all three to null at initialization? or is there different problem with doing that?

No, there is no problem with that: you could say it is wasteful since you may be initialising something to NULL just to change its value to something else right after, but it doesn't matter much (although it isn't very elegant/clean).

Setting these values to NULL from `locate_desktop()` and `locate_monitor()` makes more sense in my opinion since these functions already set `loc` if something is located. (they probably were meant to set `loc` also when nothing is located.)
Making the change there also prevents these functions from being misused again in the future and fixes the bug everywhere this function is used (it also limits the potential side effects of this change to only where these functions where used).

**Comment by ortango** [comment]
thanks for taking the time to explain that to me, much appreciated.
