### ISSUE TITLE
[Feature Request] Maintain aspect ratio of floating windows when resizing

### ISSUE THREAD

**Issue by borosai** [baskerville/bspwm#1217]
I feel the current behavior is the correct default behavior: resize floating windows freely. However, in certain situations it would be nice to be able to resize a floating window while maintaining its aspect ratio (in my case, video content). 

Without getting into the implementation (which I don't understand anyway), something like this would be ideal (only mouse related):
super + button3 -> resize freely (current behavior)
super + shift + button3 -> resize while maintaining aspect ratio

Honestly, this would be a nice enhancement to see, but it's not important since I currently just resize carefully to eliminate the black bars. Still, if it's not too much of a pain to implement, it would be great.

**Comment by alex3kov** [comment]
Would be nice - for example i3 resizes mpv proportionally by default (no idea how).

**Comment by ortango** [comment]
if you have `honor_size_hints` on then windows should resize based on their hints. `mpv` for instance would act as described. above.

otherwise you can use `wmutils` to mimic the behavior; either by a keybind that resizes based on current size and a multiplier(+1/10,*2,etc).
or by subscribing to `pointer_action` and watching for, say, `resize_corner`, capturing the size at `begin` and resizing one dimension to match the original ratio at `end`.

**Comment by alex3kov** [comment]
`honor_size_hints` works for mpv (it's `bspc config honor_size_hints true` in config)

**Comment by borosai** [comment]
@ortango
Thanks for the tips. honor_size_hints is something I always disable because I prefer my windows to be tiled evenly, so I hadn't considered this setting as a way to deal with resizing these specific windows.

I'll focus on the methods you've mentioned, and I suppose it's fine to close this issue.

**Comment by ortango** [comment]
i don't know if you happened to see this PR come in, but it seems like exactly what you would like: #1251
