### ISSUE TITLE
Bspc quit does not terminate all processes spawned in bspwmrc

### ISSUE THREAD

**Issue by Filip62** [baskerville/bspwm#1236]
**I am not sure if this is a bspwm issue, so please correct me if I am wrong.
When I quit Bspwm with `bspc quit`, some processes spawned in bspwmrc do not terminate.**

Processes spawned by bswmrc, while bspwm is still running:
![htop](https://user-images.githubusercontent.com/58399088/101984671-268ba380-3c83-11eb-8b4a-e309c4b470a7.png)

(Ignore the rtkit deamon)Processes that did not get terminated after `bspc quit`:
![htoptty](https://user-images.githubusercontent.com/58399088/101985092-13c69e00-3c86-11eb-84b1-11cc21bdb450.png)

- `clipnotify` process is gone but `clipmenud` stayed.
- `redshift-gtk` process is gone but `redshift -v` stayed.

Arch Linux Bspwm 0.9.10

bspwmrc:
``` bash
#!/bin/bash

bspc monitor HDMI-0 -d I II III IV
bspc monitor DVI-I-0 -d V VI VII VIII

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
# bspc config pointer_follows_focus true

bspc config automatic_scheme longest_side

# bspc rule -a "Doom Emacs" state=tiled
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^3'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# source the colors.
#. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
#bspc config presel_feedback_color "$color1"

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#81a1c1"
bspc config presel_feedback_color "#2e3440"

wmname LG3D
xset r rate 200 50

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -fx 'polybar bspwm' > /dev/null || polybar bspwm &
pgrep -fx 'polybar bspwm2' > /dev/null || polybar bspwm2 &
# for m in $(polybar --list-monitors | cut -d":" -f1); do
#     MONITOR=$m polybar bspwm &
# done
pgrep -f nitrogen > /dev/null || nitrogen --restore &
pgrep -x dunst > /dev/null || dunst &
pgrep -x unclutter > /dev/null || unclutter &
pgrep -f redshift-gtk > /dev/null || redshift-gtk &
pgrep -x flameshot > /dev/null || flameshot &
pgrep -f clipmenud > /dev/null || clipmenud &
pgrep -x picom > /dev/null || picom --experimental-backends &

export PIDSWALLOW_TERMINAL='alacritty'
export PIDSWALLOW_SWALLOW_COMMAND='bspc node $pwid --flag hidden=on'
export PIDSWALLOW_VOMIT_COMMAND='bspc node $pwid --flag hidden=off'
export PIDSWALLOW_PREGLUE_HOOK='bspc query -N -n $pwid.floating >/dev/null && bspc node $cwid --state floating'
pgrep -f 'pidswallow -gl' > /dev/null || pidswallow -gl &

```

**Comment by emanuele6** [comment]
bspwm is not supposed to do it. bspwmrc is just a script that is run when bspwm starts or when you execute `bspc wm -r`.

The other processes probably die because they lose connection to X after bspc terminates.

I don't use `clipnotify` or `redshift-gtk` (I don't even know what they are), but try to see if you can find in their help messages or `man` pages if there is an option to make them die if X terminates.

For example:
`urxvtd` (`urxvt` daemon) can run independently of `X`; if you start it with `urxvtd &`, it will stay alive even if X terminates
but, if you use the `-o` option (`urxvtd -o &`), it will create a connection with X when starting and, whenever it loses it, it will die.

**Comment by Filip62** [comment]
Well since the bspwmrc script is run by bspwm when started, I thought it is also terminated by bspwm when stopped.

It is still running since it has jobs in background right? Unless they are disowned somehow.

Well it is only a problem when restarting bspwm, so I could implement some basic checking functionality to kill leftovers. Seemed janky though.

**Comment by emanuele6** [comment]
no, it is not still running.
try to run your `bspwmrc` in a terminal; it terminates.

**Comment by Lythenas** [comment]
I use something like this in bspwmrc to work around this issue when restart bspwm:

```sh
# starts an "app" if it is not already running
start_app() {
  log "Starting app $@"
  pgrep "$1" || "$@" &
}

# kills (if it is already running) and starts a "service"
# note this will kill ALL instance of the running "service"
start_service() {
  log "Starting service $@"
  killall "$1" 2>/dev/null
  "$@" &
}

start_service sxhkd
start_app firefox
```

**Comment by emanuele6** [comment]
@Lythenas that will kill the "services" when reloading `bspwm`; that is not what he wants, he wants them to die when `bspwm` terminates. He already uses `pgrep ... ||` on all the processes he starts so this is basically the same he's already doing.

@Filip62, A thing you could try is this I just figured out (I also tested it, it works):

```bash
#!/bin/bash

bspc monitor HDMI-0 -d I II III IV
bspc monitor DVI-I-0 -d V VI VII VIII

bspc config border_width         2
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
# bspc config pointer_follows_focus true

bspc config automatic_scheme longest_side

# bspc rule -a "Doom Emacs" state=tiled
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^3'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# source the colors.
#. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
#bspc config normal_border_color "$color1"
#bspc config active_border_color "$color2"
#bspc config focused_border_color "$color15"
#bspc config presel_feedback_color "$color1"

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#81a1c1"
bspc config presel_feedback_color "#2e3440"

wmname LG3D
xset r rate 200 50

pgrep -x sxhkd > /dev/null ||  { sxhkd & }
pgrep -fx 'polybar bspwm' > /dev/null || { polybar bspwm & }
pgrep -fx 'polybar bspwm2' > /dev/null || { polybar bspwm2 & }
# for m in $(polybar --list-monitors | cut -d":" -f1); do
#     MONITOR=$m polybar bspwm &
# done
pgrep -f nitrogen > /dev/null || { nitrogen --restore & }
pgrep -x dunst > /dev/null || { dunst & }
pgrep -x unclutter > /dev/null || { unclutter & }
pgrep -f redshift-gtk > /dev/null || { redshift-gtk & }
pgrep -x flameshot > /dev/null || { flameshot & }
pgrep -f clipmenud > /dev/null || { clipmenud & }
pgrep -x picom > /dev/null || { picom --experimental-backends & }

export PIDSWALLOW_TERMINAL='alacritty'
export PIDSWALLOW_SWALLOW_COMMAND='bspc node $pwid --flag hidden=on'
export PIDSWALLOW_VOMIT_COMMAND='bspc node $pwid --flag hidden=off'
export PIDSWALLOW_PREGLUE_HOOK='bspc query -N -n $pwid.floating >/dev/null && bspc node $cwid --state floating'
pgrep -f 'pidswallow -gl' > /dev/null || { pidswallow -gl & }

# if no processes where started by this script, we are done
[ -z "$(jobs -p)" ] && exit 0

# wait for bspwm to terminate
bspc subscribe > /dev/null

# kill all the processes started by this script
kill $(jobs -p)
```
 
`bspc subscribe` will stay alive until `bspwm` terminates; when `bspc subscribe` terminates, the script will continue and `bash` will kill all the processes that were spawned.
Also note that I put commands that i want to run in the background in `{}` this is because as it was written before `pgrep` would run in the background with the other commands (which would mess-up the `[ -z "$(jobs -p)" ]` check) and the pids outputed by `jobs -p` would not be the pid of the launched deamons, but of the background subshells from which they are run.
NB: I suggest to explicitly use `bash` for this solution, process managing is not well defined in POSIX from my experience.

I think this is a pretty clever solution and it will solve your problem of processes not terminating after `bspwm` terminates @Filip62 .

**Comment by Filip62** [comment]
I'm sure this will be perfect, thank You @emanuele6 .
