### ISSUE TITLE
bspwm rules do not work on stalonetray

### ISSUE THREAD

**Issue by alex3kov** [baskerville/bspwm#1239]
`bspc rule -a Zathura hidden=on` -> `zathura` starts hidden.\
`bspc rule -a stalonetray hidden=on` -> `stalonetray` starts visible.\
xprop of stalonetray:
```
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_STRUT_PARTIAL(CARDINAL) = 0, 0, 24, 0, 0, 0, 0, 0, 1896, 1919, 0, 0
_NET_WM_STRUT(CARDINAL) = 0, 0, 24, 0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_NORMAL, _NET_WM_WINDOW_TYPE_DOCK, _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_DESKTOP(ATOM) = undefined atom # 0xffffffff, undefined atom # 0xffffffff
_NET_WM_STATE(ATOM) = _NET_WM_STATE_STICKY, _NET_WM_STATE_SKIP_TASKBAR, _NET_WM_STATE_STICKY, _NET_WM_STATE_SKIP_TASKBAR
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x1, 0x0, 0x0, 0x0
STALONETRAY_TIMESTAMP(STALONETRAY_TIMESTAMP) = 0x73
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING
_NET_SYSTEM_TRAY_ORIENTATION(_NET_SYSTEM_TRAY_ORIENTATION) = 0x1
WM_COMMAND(STRING) = { "stalonetray", "-c", "/home/user/dotfiles/stalonetrayrc" }
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		user specified location: 1896, 0
		user specified size: 24 by 24
		program specified minimum size: 24 by 24
		program specified maximum size: 24 by 24
		program specified resize increment: 24 by 24
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_CLASS(STRING) = "stalonetray", "stalonetray"
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: False
		Initial state is Normal State.
WM_NAME(STRING) = "stalonetray"

```

**Comment by emanuele6** [comment]
It's a dock; `bspwm` won't manage it by default; since it is not managed, even if it's hidden, it won't matter.

You can make `bspwm` manage it with a `manage=on` rule (then the hidden flag would work on it), but I bet you don't wan't it to behave like this (using `polybar` as example):
* [video1](https://www.youtube.com/watch?v=cOw5ceMUkLE)
* [video2](https://www.youtube.com/watch?v=kBaQ_n9nzmQ)

Just use the api provided by your dock to hide it (in `polybar`, it is `polybar-msg -pid PID_OF_THE_BAR cmd (toggle|hide|show)`).
If `stalonetray` (I have never heard of it so I don't know if it has it) doesn't have an api to do so, just use the `hide` and `show` subcommands of [`xdo`](https://github.com/baskerville/xdo) to unmap and map the dock; example:

```bash
# use this command to hide it
xdo hide -Nstalonetray -nstalonetray
# use this command to show it
xdo show -Nstalonetray -nstalonetray
```

**Comment by alex3kov** [comment]
If I add `manage=on` then bspwm hides stalonetray on startup (and hits #1147 issue right away - empty space at the top), but then `xdo show -Nstalonetray` command can't bring it back. Looks like there's no way to toggle `hidden` flag at runtime with `bspc` either - matching by class is available only in rules unless I'm missing something in man page.\
I do have a workaround script [here](https://gitlab.com/alex3kov/scripts/-/raw/master/toggle_stalonetray.sh), just thought doing it all with `bspc` would be more "proper".

**Comment by emanuele6** [comment]
> just thought doing it all with bspc would be more "proper".

I would not: it's a bar, not a Window; bspWm is a Window manager.

Also I don't understand why you tried using a `manage=on hidden=on` rule. I thought I made it clear why you wouldn't want to make `bspwm` manage it. Welp.

> `but then `xdo show -Nstalonetray` command can't bring it back

Obviously. The window was never unmapped (`xdo hide`), it was just being hidden by `bspwm`; `xdo show -Nstalonetray` doesn't do anything because the `stalonetray` "window" is already mapped, you can see it only because it's hidden by `bspwm`.
If you want to unhide it *et cetera* while it's being managed by `bspwm` (again, I don't understand why you even tried doing it; it's nonsensical), you need to use `bspc` to change the `hidden` flag of the managed window; e.g. like so:
```bash
# hide
bspc node "$(xdo id -Nstalonetray -nstalonetray | head -1)" -g hidden=on
# unhide
bspc node "$(xdo id -Nstalonetray -nstalonetray | head -1)" -g hidden=on
# toggle hidden
bspc node "$(xdo id -Nstalonetray -nstalonetray | head -1)" -g hidden
```

**Comment by alex3kov** [comment]
Chill it with the condescension @emanuele6 , not everyone is a bspwm wizard, having domain-specific knowledge doesn't make you smart.\
#1147 is my reason to try to manage stalonetray with bspwm instead of `xdo`

**Comment by emanuele6** [comment]
I recorded two videos showing you what will happen if you make `bspwm` manage a dock; I told you how you can approach the problem; I explained to you why `xdo show` wasn't unhiding the window; and I even showed you how you can use `bspwm` to hide your bar (which, again, it's nonsensical) just because you tried doing it.

That was indeed not very smart of me; I should use my time better.
