### ISSUE TITLE
[BEHAVIOUR CHANGE] Allow sending a node to its parent if the parent has a preselection.

### ISSUE THREAD

**Issue by emanuele6** [baskerville/bspwm#1254]
Currently, `bspwm` won't allow you to send a node to its direct parent.

The current behaviour unnecessarely makes implementing this kind of hotkey **EXTREMELY** tedious since there is no reliable way (without using a temporary desktop/monitor) to make a node not be the direct child of the `root` node in case it is:

```bash
# note: these hotkeys don't work correctly if the focused node is a
#         direct child of the root node.
super + {Left,Up,Right,Down}
	bspc node '@/' -p {west,north,east,south}; \
	bspc node -n '@/' \
	    || bspc node '@/' -p cancel
```

`bspwm` should just send a child node to its parents if the parent has a preselected area (at least, if that would result in changing the children order, the split ratio or the split type of the parent, but I think it's best to just do it unconditionally if there is a preselection since the command can do something: it can removed the preselection).

**Comment by emanuele6** [comment]
workaround implementation: https://gist.github.com/emanuele6/9eab3f7867ea446f5e9bc6ce5561ebdb

**Comment by emanuele6** [comment]
> since there is no reliable way (without using a temporary desktop/monitor) to make a node not be the direct child of the root node in case it is

I figured out a reliable way to do that and run `bspc node '@/' -p "$dir"; bspc node -n '@/'` with the behaviour I requested!

```bash
bspc node '@/' -p "$dir"
bspc node -n '@/' || {
    bspc node '@/' -p cancel
    bspc node '@brother' -p "$dir"
    bspc node -n '@brother' \
        || bspc node '@brother' -p cancel
}
```

Still, I think it would make sense to change the behaviour to what I requested.

**Comment by ortango** [comment]
at the risk of not adding anything helpful:

>Still, I think it would make sense to change the behaviour to what I requested.

isn't the issue that unlinking the node would change(or remove) the parent node(which is the destination node in the problem case)? also, the preselection would get canceled anyway.

____

[here are two different *example* workarounds](https://gist.github.com/ortango/e3d7d219a435bb27f840ad1e2002ccbf). one is similar to the first workaround you posted. "preselection" is part of the script. it `rotate`s instead of `transfer`s when appropriate. mostly just an interesting way of getting the rotation.

the other script is a more universal `node -n` replacement. if the destination is the parent node (and has a preselection) then it moves the preselection and the destination to the brother node. otherwise it just transfers the node as normal.

in either case the scripts are meant to take any destination, and then do the "correct" thing as far as parent destinations.

**Comment by emanuele6** [comment]
Your `just-transfer.sh` script does basically the same thing as the [second solution I posted](https://github.com/baskerville/bspwm/issues/1254#issuecomment-770934308)
> in either case the scripts are meant to take any destination, and then do the "correct" thing as far as parent destinations.
But your `presel-and-transfer.sh` (similar to my first workaround) is flawed because it's using a preselection on `dest` + `node -n dest` if it can (which is fine); and, otherwise, it rotates `dest` by the appropriate angle, but, when you do that, you should also rotate `"$node:@brother"` by the opposite angle.

I get why `bspwm` decides to not send a node to its parent, but I don't think the current behaviour is useful in any way since preselections exist.

**Comment by ortango** [comment]
i had another idea, but am hesitant to post it since it is along the same lines as moving the preselection: you try to preserve the parent destination node by placing a receptacle.

    dest=$(bspc query -N -n $1) || exit
    if ! bspc node -n $dest; then
        bspc node $dest -i &&
            { bspc node -n ${dest}#@/1.leaf.!window || bspc node -n ${dest}#@/2.leaf.!window; }
    fi

i did not bother with checking if the destination is the parent, but only from laziness. i think the main issues here are: getting the actual receptacle node isn't so clean, and since the commands can't be chained you get unnecessary resizing.

i don't think either of those things are an issue when using insert_node directly in bspwm though. my "patch" to test this is simple (a single line), and probably very bad. i am not a coder, and also didn't test this beyond seeing if the idea worked out well enough. at the very least i am not destroying the temporary node if the transfer fails, which probably should be done.

[my attempt at a simple fix](https://gist.github.com/ortango/57f297237d761c74661764fc00404d6e)
