### ISSUE TITLE
Android Studio toolbar menus floating in the center of desktop

### ISSUE THREAD

**Issue by Filip62** [baskerville/bspwm#1255]
In Android Studio if I choose any of menubar items like File, Edit, View, etc, they all float in the center of the desktop.
Also all menus within those menus do the same.

I don't have this issue with CLion, so It is probably Android Studio's fault, but still.

Any suggestions?

Thanks.

**Comment by dieggsy** [comment]
@Filip62 you might be able to get info for those items by running something like
```shell
sleep 5 && xprop -id $(xprop -root _NET_ACTIVE_WINDOW | grep -Po "(?<=#).*")
```
Then opening such a menubar item and hovering your mouse over it before the timeout ends. (I suggest this because those items tend to go away after losing focus, so a regular call to `xprop` might not work).

Then you can create rules or external rules based on that info. Hope that helps, I only tested it on Firefox menu items.

**Comment by Filip62** [comment]
Actually I just copied this line `bspc rule -a 'jetbrains-studio:sun-awt-X11-XWindowPeer' manage=off` from your config and it's all good, thank you very much.

**Comment by dieggsy** [comment]
@Filip62 great! glad to be of help ...I forgot I'd done that, to behonest
