### ISSUE TITLE
[Question] How to float a window with specific size

### ISSUE THREAD

**Issue by ivanddm** [baskerville/bspwm#1273]
Is it possible to set the state of a window/node to floating state and specific window size? In i3 I can chain `floating toggle` and `resize set width height` to achieve this.

I haven't been able to do the same in bspwm. At the moment, after floating a window I have to adjust the size manually.

Thanks in advance!

**Comment by emanuele6** [comment]
In `bspwm`, you can only resize a window to a specific size when the window is created (using a rule).

`node -z` is a command that allows you to resize a node that is already in the tree by moving a corner or an edge of that node by (dx, dy) pixels. 

Windows that are already in the tree cannot be absolutely resized to a specific size using a simple `bspwm` command though; this is because features are implemented as `bspwm` command only if strictly necessary: resizing a tiled `bspwm` node is something that needs to be implemented in `bspwm`, an external X utility program can't do that, but, resizing the rectangle of an X window can be done by external utilities.

You can use, for example: [`xdotool`](https://github.com/jordansissel/xdotool) or `wtp` \(from [`wmutils`](https://github.com/wmutils/core)\) to what you want to do.

[`xdotool`](https://github.com/jordansissel/xdotool): `width: 200; height: 300`:
```sh
#!/bin/sh
bspc node -t floating
xdotool getactivewindow windowsize 200 300
```
`wtp` and `pfw` \(from [`wmutils`](https://github.com/wmutils/core)\): 
```sh
#!/bin/sh
bspc node -t floating
wtp 0 0 200 300 "$(pfw)"
```

**Comment by ivanddm** [comment]
Thanks, @emanuele6, either `xdotool` or `wmutils` work great and I can accomplish what I was looking for.
