### ISSUE TITLE
An empty node?

### ISSUE THREAD

**Issue by DoubleClick7** [baskerville/bspwm#1299]
If, say, I have two windows open in the current desktop, and I run `bspc node -f next.active` while having the first window open, it seems like the focus shifts to nothing before going to the second window. For example, suppose I have opened terminal windows 'A' and 'B' in that order. So now the focus is on B. I run `bspc node -f next.active` and then the focus is on 'A' so I can type on it. Then I run `bspc node -f next.active` again and the focus disappears, I am unable to type in any window. Running the command again switches the focus to 'B' again. So, focus shifts like B > A > nowhere > B > A > nowhere...

This problem is bugging me since forever. Is there a hidden empty node or something?

**Comment by ortango** [comment]
since d87e6c0f773e189a3a62b2d066b982b3a4e2bd56, you can get non-leaf nodes from next/prev. you need to use `{next,prev}.active.window` to select only windows.

the invisible node is an internal node - the parent of the two windows present on the desktop.

a curiosity from your description of the issue though:
>two windows open in the current desktop, and I run bspc node -f {next,prev}.active
`.active` should not be matching multiple nodes on a single desktop (or monitor). `.active` should match the active (the node that would have focus if the monitor had focus) windows on visible monitors. but, maybe this behavior had changed at some point, so what version of bspwm are you running?

**Comment by DoubleClick7** [comment]
0.9.10-1
.active.window doesn't work.
Also, I didn't mean `{next,prev}`, but `next`. I copy-pasted that from my sxhkd config.

**Comment by DoubleClick7** [comment]
Ok I don't know why but `{next,prev}.window.local` in the `sxhkd` config totally works.

**Comment by ortango** [comment]
>> active.window doesn't work.
>> Also, I didn't mean {next,prev}, but next. I copy-pasted that from my sxhkd config.
> Ok I don't know why but `{next,prev}.window.local` in the `sxhkd` config totally works.

reread my comment (i will edit it to fix the quoting issue from the original). i think you do not understand what active does.

**Comment by DoubleClick7** [comment]
Yeah, I actually don't know.
