### ISSUE TITLE
Hiding window borders

### ISSUE THREAD

**Issue by DashCruft** [baskerville/bspwm#1337]
Hello,

I don't know if this is a feature already nor it's not a feature that has been created, but I want to remove the white borders completely for active windows on my bspwm. This issue occurs If the window is active; If its not, I don't see any borders.
![image](https://user-images.githubusercontent.com/59381835/140841711-d98b0ddc-1fff-431e-8260-784027815dbe.png)

I tried this script bellow but it doesn't remove the borders completely:
`bspc config -n $(bspc query -N -n) border_width 0`

Any help is appreciated!
Thanks

**Comment by emanuele6** [comment]
> I tried this script bellow but it doesn't remove the borders completely:
> `bspc config -n $(bspc query -N -n) border_width 0`

No, it does remove the border completely.

> ![](https://user-images.githubusercontent.com/59381835/140841711-d98b0ddc-1fff-431e-8260-784027815dbe.png)

Is that supposed to be the corner of a window? `bspwm` does not round window corners. Are you sure you are actually using `bspwm` and not some patched version?

Can you tell us your `bspwm` version, provide a `bspwmrc` that can reproduce this issue, and maybe name a program of which the windows are affected by this problem so that we can actually try to reproduce it? (see: [CONTRIBUTING.md](https://github.com/baskerville/bspwm/blob/master/doc/CONTRIBUTING.md))

**Comment by DashCruft** [comment]
I use jounerburg/picom to use rounded borders for bspwm and it works smoother and way better.

**Comment by DashCruft** [comment]
I use `jonaburg/picom` to use rounded borders for `bspwm` and it works smoother and way better.

I don't use `bspwm`'s patched version for rounded borders.
Instead, I use the official pacman version of `bspwm` which at this moment is **0.9.10-1** 

I troubleshooted everything myself but unfortunately this issue is not caused by any sorts of third party applications during my test on a sandbox virtual machine of Arch Linux and BSPWM.

**Comment by emanuele6** [comment]
As I said, that `bspc config -n $(bspc query -N -n) border_width 0` does indeed remove the border of `bspwm` leaves completely.

I have had an hotkey that toggles the border of the focused window and i have never had this problem:
```bash
# Toggle border of the focused window
super + shift + comma
	[ "$(bspc config -d focused.monocle -n 'focused.!floating.!fullscreen.window' borderless_monocle)" = true ] \
	    && [ "$(bspc config borderless_monocle)" = true ] \
	    && exit 1; \
	bw=$(bspc config -n focused.window border_width) \
	    || exit 1; \
	if [ "$bw" = 0 ]; \
	    then bspc config -n focused.window border_width "$(bspc config border_width)"; \
	    else bspc config -n focused.window border_width 0; \
	fi
```

----

`bspc config focused_border_color`: `#458588`
`bspc config normal_border_color`: `#32302F`
`bspc config border_width`: 3

<details><summary>screenshot with border on</summary><p>

![with_border](https://user-images.githubusercontent.com/20175435/141012661-cd1d3640-ff38-4146-99d0-ae7bbdd81412.png)
</p></details><details><summary>screenshot with border off</summary><p>

![without_border](https://user-images.githubusercontent.com/20175435/141012690-497fc05c-1421-4675-97da-fdf8cd66138f.png)
</p></details>

As you can see from these screenshots, no thin border line can be seen. The background colour of the borderless floating terminal (`#252323`) is exactly the same as the tiled terminal behind it and can't be distinguished.

<details><summary>here is also a video that captures the whole screen while i move stuff around</summary><p>

https://user-images.githubusercontent.com/20175435/141014293-98a4f569-6f02-48b0-a80b-fbb7f54437e3.mp4
</p></details>

---

> unfortunately this issue is not caused by any sorts of third party applications during my test on a sandbox virtual machine of Arch Linux and BSPWM.

Does that mean that you tried it without `picom`? Can you give me steps on how to reproduce this since you tried it in a minimal installation?

**Comment by DashCruft** [comment]
> As I said, that bspc config -n $(bspc query -N -n) border_width 0 does indeed remove the border of bspwm windows completely.

I totally agree with you on this because the border size DOES go to 0 but for some reason, it still shows it for the ACTIVE window that I click on. The video I attached also shows it all.


> Does "is not caused by any sorts of third party applications" mean that you tested it without picom? Can you give me steps on how to reproduce the problem since you were able to reproduce it on a minimal installation?

I just recorded a video to show the issue and it is indeed without any picom process as shown on the left side terminal:
In case you also need my `bspwm` file, here you go:
https://sourceb.in/uWISkfxPQs

https://user-images.githubusercontent.com/59381835/141022708-19143714-4c51-4fa4-a53c-3323ff44b6d1.mp4

**Comment by DashCruft** [comment]
No way! It actually worked :O

> bspc config -n $(bspc query -N -n) border_width 0 is a (hacky and bad, since the command substitution is unquoted causing a syntax error when the query has no result and since it could have just been replaced by the focused node selector) command line that, when it's run, sets the border_width setting of the focused node and all of its decendants to 0; it does not set the default value of the border_width to 0.

Thank you so much for explaining this. Now I have a better idea about what should I use and what should I not with perfect reasoning thanks to you.

>bspc query -N -n gets the id of the focused node and bspc config -n "$node" border_width 0 updates the value of the border_width setting for $node (and all of its decendants) to 0.

Ah yes. This perfectly makes sense why my focused window's border was suffering cuz of this.

>It does not make sense to run that in bspwmrc since at startup you don't have any window open (not that it would make sense to run it in bspwmrc even if there were any windows open).

Yep, Thanks to the perfect explaining of yours, now I know when to use that property and option.

> Use bspc config border_width 0 if you want to set the default value of border_width to 0 so that all your new windows will have a border_width of 0 when they are managed.

Yep! I can confirm this solves my issue. Again, thanks for your attention and help 💜

**Comment by chris-aeviator** [comment]
I have had some unremovable borders for some while now...I'm free of them for most applications, but e.g. nautilus (file manager that comes with gnome) or dunst (notification system) has real ugly borders I cannot get rid of. I can confirm it's not GTK borders (see borderless gnome-calendar)

![image](https://user-images.githubusercontent.com/11522213/145665008-b6b9cd20-7a19-45cb-b2b5-9924ce0521c0.png)

![image](https://user-images.githubusercontent.com/11522213/145665025-39496a0a-477a-41b6-81b4-4a6966232df3.png)

Anyone has any ideas???
