### ISSUE TITLE
Does monocle state not count as a valid state?

### ISSUE THREAD

**Issue by agoodfellow123** [baskerville/bspwm#1365]
Hello, I want to focus the next node with a keybinding only if the current layout is monocle, I have the following code:

super + Left
	if bspc query -N -n focused.floating > /dev/null; then \
		bspc node -f next.local.floating; \
	else if bspc query -N -n focused.monocle > /dev/null; then \
		bspc node -f next.local.tiled; \
	else \
		bspc node -f west; \
	fi

The first if part works as intended however the second part (else if part) doesn't seem to work. I checked bspc manual and realized that monocle doesn't work like the rest of the window states. Is there a solution to my problem?

**Comment by emanuele6** [comment]
`monocle` is not a `state` (`state` is a window property and can be `fullscreen`, `tiled`, `pseudo_tiled` or `floating`), it's a layout.

The `layout` a property of the `desktop`, not of the `node` or window.

If you want to check if you are in a `monocle` desktop, you should use `bspc query -D focused.monocle` (or `bspc query -D focused.user_monocle` if you don't want to count `single_monocle` as `monocle`), i.e. use of `-D` instead of `-N` since you are selecting a `desktop` and not a `node`.

(`-d`/`-n` are not really needed if you are going to discard `stdout` with `> /dev/null` and only want to check if the selector matched something, but it doesn't hurt to have them.)

---
Your shell code is also invalid, you cannot write:

```bash
if x; then
    y
else if a; then
    b
else
    c
fi
```

It has to be either:
```bash
if x; then
    y
else
    if a; then
        b
    else
        c
    fi
fi # note the second `fi'; you need a `fi' to close every `if'
```

Or, more commonly:
```bash
if x; then
    y
elif a; then # using `elif' instead of `else if'
        b
else
    c
fi
```

The code you wrote would not work regardless of your `monocle` misunderstanding if you write it like that since it is not even valid.

Also note that, in `sxhkd`, you need to prepend every line of code with a space or tab and have a `\` as the last character of all the lines but the last one.

---
Your `sxhkd` hotkey should be written like so (I'm just fixing the mistakes, not simplifying your code):

```bash
# NB: it's important that you use `.!hidden` in your `node -f next`
#      commands; otherwise, the will get stuck if a hidden window is
#      present.
# NITPICK: I would use
#            next.local.!hidden.!fullscreen.!floating.window
#          instead of
#            next.local.!hidden.tiled
#          so that your selector is allowed to match pseudo_tiled
#          (if you use .tiled, pseudo_tiled windows would be skipped)
#          in some cases you may want to use .tiled, but here, I think
#          it makes more sense to use .!fullscreen.!floating.window

super + Left
	if bspc query -N -n focused.floating > /dev/null; then \
	    bspc node -f 'next.local.!hidden.floating'; \
	elif bspc query -D -d focused.monocle > /dev/null; then \
	    bspc node -f 'next.local.!hidden.tiled'; \
	else \
	    bspc node -f west; \
	fi
```

As an advanced user, I would personally write your hotkey as simply:

```bash
super + Left
	bspc node focused.floating -f 'next.local.!hidden.floating' \
	    || bspc node '@focused.monocle:/#focused' -f 'next.local.!hidden.tiled' \
	    || bspc node west -f
```

**Comment by agoodfellow123** [comment]
Oh, sorry for the mistakes, I forgot I had to use elif instead of else if, haven't written shell in a while and the `\` was removed by github. Thank you for the solution however sadly I couldn't make it work `elif bspc query -D -d focused.monocle > /dev/null; then \` part just doesn't want to cooperate. Anything else you can suggest?

**Comment by emanuele6** [comment]
@agoodfellow123, well your code was wrong before. The code I gave you is correct and will work.

> however sadly I couldn't make it work elif bspc query -D -d focused.monocle > /dev/null; then \ part just doesn't want to cooperate.

Do note that, even though `.monocle` is a one and a half year old feature (introduced by 853bb7345252d84e1ee33ae0b8ccde1a5b4b91b2), it is not present in the most recent release of `bspwm` \([0.9.10](https://github.com/baskerville/bspwm/releases/tag/0.9.10) released on 02 Aug 2020\).

If you want to use that, you will have to compile `bspwm` from source code using the code available on the [master](https://github.com/baskerville/bspwm/tree/master) branch of this repository.
I think that, if you are using an [ArchLinux](https://archlinux.org/) based GNU/Linux distribution, you could install the "git master" version of `bspwm` using the [`bspwm-git`](https://aur.archlinux.org/packages/bspwm-git) AUR package (it's basically the same thing as downloading the repo and building from source, but it's automated).

---

> Anything else you can suggest?

In versions of `bspwm` that don't have `.monocle`/`.user_monocle`/`.tiled`/`.user_tiled`, you could use a JSON parsing tool to parse the dump output of `bspc query -T` for the desktop you want to target and perform the checks you need on the json.

Example using `jq`:

```bash
# using .monocle
bspc query -D focused.monocle > /dev/null
# using jq
bspc query -T -d | jq -e '.layout == "monocle"' > /dev/null
```
```bash
# using .!monocle
bspc query -D 'focused.!monocle' > /dev/null
# using jq
bspc query -T -d | jq -e '.layout != "monocle"' > /dev/null
```
```bash
# using .tiled
bspc query -D focused.tiled > /dev/null
# using jq
bspc query -T -d | jq -e '.layout == "tiled"' > /dev/null
```
```bash
# using .!tiled
bspc query -D 'focused.!tiled' > /dev/null
# using jq
bspc query -T -d | jq -e '.layout != "tiled"' > /dev/null
```
```bash
# using .user_monocle
bspc query -D focused.user_monocle > /dev/null
# using jq
bspc query -T -d | jq -e '.userLayout == "monocle"' > /dev/null
```
```bash
# using .!user_monocle
bspc query -D 'focused.!user_monocle' > /dev/null
# using jq
bspc query -T -d | jq -e '.userLayout != "monocle"' > /dev/null
```
```bash
# using .user_tiled
bspc query -D focused.user_tiled > /dev/null
# using jq
bspc query -T -d | jq -e '.userLayout == "tiled"' > /dev/null
```
```bash
# using .!tiled
bspc query -D 'focused.!user_tiled' > /dev/null
# using jq
bspc query -T -d | jq -e '.userLayout != "tiled"' > /dev/null
```

**Comment by agoodfellow123** [comment]
I see so that's why it didn't work on my end, thank you for clarifying that! No rush though I can wait for the new Arch repository version to come out, then I'll add that keybind. By the way, do you know when the Arch repository version will have an update? Can't be too far right, I mean it apparently has almost been two years already.

**Comment by emanuele6** [comment]
> By the way, do you know when the Arch repository version will have an update? Can't be too far right, I mean it apparently has almost been two years already.

The version on the ArchLinux repositories is not outdated. It is simply using the last official release: bspwm version [0.9.10](https://github.com/baskerville/bspwm/releases/tag/0.9.10) released 02 Aug 2020.
 
 There has not been any other official release of `bspwm` since then.
 
 Until there is an official `bspwm` release (e.g. 0.9.11), distributions won't update their packages.

**Comment by agoodfellow123** [comment]
Got it, thank you!
