### ISSUE TITLE
Why bspwm ignores first WM_CLASS when matching rules

### ISSUE THREAD

**Issue by 8bitkitkat** [baskerville/bspwm#1370]
Given `qemu-system-x86_64`, which reports `WM_CLASS(STRING) = "qemu", "Qemu-system-x86_64"`.
Only the rule `bspc rule -a Qemu-system-x86_64 state=floating` gets applied, but `bspc rule -a qemu state=floating` does not.

**Comment by emanuele6** [comment]
`bspc rule -a qemu state=floating` tells `bspwm` to add a rule that applies `state=floating` to windows that have a "qemu" as their class name (the class name is the last element of `WM_CLASS`).

That window does not have "qemu" as class name; its class name is "Qemu-system-x86_64".
"qemu" is the instance name of that window.

If you want to add a rule that matches that any window that has "qemu" as instance name regardless of the class name, you must tell `bspwm` that: any class name (`*`) and "qemu" instance name.
```sh
#!/bin/sh -
bspc rule -a '*:qemu' state=floating
```
This is not generally something that makes sense to do. The purpose of the class name is to match windows that belong to same program, and the purpose of the instance name is to distinguish kinds of subwindows of the same program; e.g.:
```sh
#!/bin/sh -
# firefox's windows hava "Firefox" has class name:
#  * the browser windows have "Navigator" as instance name
#  * the history/downloads/bookmarks management windows have "Library" as instance name
#  * the "about" windows have "Browser" as instance name
#  * generic windows (e.g. file pickers) have "firefox" as instance name

# rules are applied in order:
# this set of rules sends all Firefox windows to the seventh desktop;
#  if they are Navigator or Library windows, they will be tiled
#  otherwise they will be floating

# send all firefox windows to the 7th desktop as floating
bspc rule -a 'Firefox' 'desktop=^7' state=floating

# rules that only match Navigator and Library instance names for Firefox windows
#  and overwrite the state=floating rule with state=tiled
bspc rule -a 'Firefox:Navigator' state=tiled
bspc rule -a 'Firefox:Library' state=tiled
```

There is no convention on the names of instance names; if the program uses custom ones instead of the standard (Classname with the first letter lowercased) is up to the developer of the program and names such are "Library", etc. are aribitrarily chosen by the developer, `*:Library` could match anything.

So, if you want to use "qemu" in your rules, you would genearally use `Qemu-system-x86_64:qemu`, not `*:qemu`.

If you want to use `*:qemu` because you have multiple versions of `qemu` and they have different class names e.g. "Qemu-system-x86_64", "Qemu-system-x86", "Qemu-system-MIPS", etc. (I don't know if that is how it works.), that could be a decent use case for `*:qemu` keeping in mind that it could match `urxvt -name qemu -e ~/bin/run_qemu.sh` or anything with `qemu` instance name even if it's not `qemu`.

But, personally, I would rather use an external rule that checks the class name with a glob instead of only checking the instance name with `*:qemu`:

setup:
```sh
$ : >> ~/.config/bspwm/external_rules
$ chmod u+x -- ~/.config/bspwm/external_rules
```

bspwmrc:
```sh
bspc config external_rules_command ~/.config/bspwm/external_rules
```

~/.config/bspwm/external_rules:
```sh
#!/bin/sh -

class=$2 instance=$3

# if the class name is "Qemu-system" or "Qemu-system-something", and the
#  instance name is "qemu", apply `state=floating`
case $class in
  Qemu-system|Qemu-system-?*)
    [ "$instance" = qemu ] && printf 'state=floating\n'
esac
```

**Comment by 8bitkitkat** [comment]
Wow, thank you for such a comprehensive answer. I guess it's just a misunderstanding of what `xprop` reports; it was my understanding that a window could have multiple class names, and that is what `xprop` was reporting.

> If you want to use *:qemu because you have multiple versions of qemu and they have different class names e.g. "Qemu-system-x86_64", "Qemu-system-x86", "Qemu-system-MIPS", etc. (I don't know if that is how it works.).

That is exactly how it works. Different versions of qemu have different executables which all have different class names that express that, but they all share the same 'instance name' "qemu"; what I was trying to target with my rule. But as you say any window with the title 'qemu' would match the rule `*:qemu`.

The script you provided seems like the perfect solution to my problem, thank you, I really appreciate your help.
