### ISSUE TITLE
bspwm always assigning HDMI-0 workspace 1

### ISSUE THREAD

**Issue by nicknase27** [baskerville/bspwm#1375]
Hello, bspwm keeps setting my tv (hdmi-0) as workspace 1 despite me having 
"bspc monitor HDMI-0 -d 2" in my bspwmrc. I am using 3 displays total and the tv is on the left which sucks to be on workspace 1 which i cant change no matter what.
Ive tried switching dp0 and hdmi0 with "bspc monitor DP-0 -s HDMI-0" which would give dp0 workspaces 1-5 but then hdmi0 workspace 6 which is odd.
Hope you can kind of fix this

**Comment by emanuele6** [comment]
> Hope you can kind of fix this

It's hard to understand what you even mean (beecause of how your question is formatted and worded, but mostly because you use the word "workspace" which doesn't mean anything in `bspwm` and I can't tell for sure if you mean "desktop" or "monitor" or something else with that), but i am going to guess the problem is that you are focusing your desktops by index, instead of by name, but you think you are focusing them by name when you actually aren't and assume this is some sort of weird `bspwm` bug.

Check your `sxhkd` configuration file and your scripts; If you are selecting desktops anywhere using `^number`, that will select the desktop by index, NOT by name: `^2` selects the second desktops, not the desktop named `"2"`.

`bspc monitor HDMI-0 -d 2` will give `HDMI-0" a single monitor named "2"; "2" is just the name of that desktop it may or may not be the second desktop in the list of desktops.

If you want to select a desktop by name, you should just write the name of the desktop you want to select; without the leading `^`.

e.g.
```bash
# in sxhkd, use something like this: (selects by desktop name)
super + {0-9}
	bspc desktop {10,1-9} -f
# example:
# super+1 will selects the desktop named "1", the position of the
#  desktop in list of desktops is irrelevant.

## for your use case, do NOT use like: (selects by desktop index)
#super + {0-9}
#	bspc desktop '^{10,1-9}' -f
## super+1 will selects the first desktop, the name of the desktop is
##  irrelevant.
```

> Ive tried switching dp0 and hdmi0 with "bspc monitor DP-0 -s HDMI-0" which would give dp0 workspaces 1-5 but then hdmi0 workspace 6 which is odd.

If you added any `monitor -s` or similar commands to your `bspwmrc` file in an attempt to "workaround this bspwm bug", you can remove them: they are not necessary; just write your `sxhkd` hotkeys and scripts to focus by name instead of by index, if that is what you want to do.

**Comment by nicknase27** [comment]
Thank you very much, it turns out that the default config uses indexing which was causing this issue. I dont want to mention how many hours i spent trying to fix this and now i feel kinda stupid, this being a relatively easy fix. Ill close the issue
