### ISSUE TITLE
Refocus focused window for FOCUS_IN events on the root window

### ISSUE THREAD

**Issue by nullchilly** [baskerville/bspwm#1378]
This deals with (admittedly somewhat misbehaving) clients which use XSetInputFocus to take focus, but then don't properly restore focus. This has been observed with TK apps, but also, e.g., Steam which can lead to chromium-based undefined behavior.

I couldn't make a PR due to limited knowledge but this has been merged in [awesome](https://github.com/awesomeWM/awesome/pull/3543/commits/b5ece5bec030057a6108af46a7c9fd74a070deb5) and [i3](https://github.com/i3/i3/commit/a06e66982bc921d05b68b75f8e12323c284233d0) and shouldn't be that hard to add? https://github.com/baskerville/bspwm/blob/1560df35be303807052c235634eb8d59415c37ff/src/events.c#L343

Thanks in advanced. Fixes https://github.com/baskerville/bspwm/issues/1160

**Comment by emanuele6** [comment]
Yeah, that seems to fix the issue.

**Comment by emanuele6** [comment]
@nullchilly actually, this doesn't seem to be necessary: `flamshot gui` works just fine without the patch for me.

**Comment by emanuele6** [comment]
Oh, the issue is that when you press `Esc` in `flameshot`, the focused node doesn't regain focus, I see.

I thought the issue was just that `flameshot` wasn't showing up at all since that was what was happening for me the last time I tried to reproduce that bug 2 years ago.

Then my patch doesn't seem to actually solve the issue.

**Comment by emanuele6** [comment]
`flameshot` does not seem to trigger any `FOCUS_IN` event when you press escape.

**Comment by emanuele6** [comment]
(NB: some of these events are caused by `dunst` since `flameshot` sends notifications)

These are the events that `bspwm` receives when I open `flameshot`:
```
CreateNotify
CreateNotify
CreateNotify
ClientMessage
ClientMessage
ClientMessage
ConfigureNotify
MapNotify
FocusOut
```

And these are the events `bspwm` receives when I press `Esc`:
```
UnmapNotify
UnmapNotify
ConfigureNotify /* dunst: notification "Screenshot aborted." */
MapNotify       /* dunst: notification "Screenshot aborted." */
DestroyNotify
DestroyNotify
DestroyNotify
/* after a while */
UnmapNotify     /* dunst: notificaiton hidden */
```

These are the events it receives when I press escape:
```
UnmapNotify
UnmapNotify
DestroyNotify
DestroyNotify
DestroyNotify
ConfigureNotify
ConfigureNotify
ConfigureNotify
MapNotify /* this is dunst: notification "screenshot aborted" */
/* after a while */
UnmapNotify /* this is dunst: notification hidden */
```

---
<details><summary>How I got these results</summary><p>

* patch:
  ```diff
  diff --git a/src/events.c b/src/events.c
  index 3b82c96..951b05c 100644
  --- a/src/events.c
  +++ b/src/events.c
  @@ -40,6 +40,15 @@ uint8_t randr_base;
   void handle_event(xcb_generic_event_t *evt)
   {
   	uint8_t resp_type = XCB_EVENT_RESPONSE_TYPE(evt);
  +	{
  +		FILE *fh = fopen("/home/emanuele6/mylog", "a");
  +		if (fh != NULL) {
  +			fprintf(fh, "%s\n", xcb_event_get_label(resp_type));
  +			fclose(fh);
  +		} else {
  +			perror("fopen()");
  +		}
  +	}
   	switch (resp_type) {
   		case XCB_MAP_REQUEST:
   			map_request(evt);
  ```
* terminal output:
  ```bash
  bash-5.1$ >~/mylog; tail -f ~/mylog | ts %s
  1650749015 CreateNotify
  1650749015 CreateNotify
  1650749015 CreateNotify
  1650749015 ClientMessage
  1650749015 ClientMessage
  1650749015 ClientMessage
  1650749015 ConfigureNotify
  1650749015 MapNotify
  1650749015 FocusOut
  1650749018 UnmapNotify
  1650749018 UnmapNotify
  1650749018 ConfigureNotify
  1650749018 MapNotify
  1650749018 DestroyNotify
  1650749018 DestroyNotify
  1650749018 DestroyNotify
  1650749023 UnmapNotify
  ^C
  ```
* reproduction steps:
  - apply the patch (using your username instead of `emanuele6`); recompile and reinstall `bspwm`; and then run `bspc wm -r`
  - open two terminal windows running two tmux instances
  - press `^Bs` in one of them to select the instance running in the other window.
  - run `>~/mylog; tail -f ~/mylog | ts %s` in that instance
  - press `^Bs` to go back to the other instance (we are doing this to avoid seeing extra events in the output caused by switching focus between the two windows)
  - run `flameshot gui` from that tmux instance
  - after a couple seconds, press escape
  - go back to the other tmux instance and press `^C`
</p>
</details>

---

Are you sure this actually fixes the issue for other window managers? I don't see how that could happen if `flameshot` doesn't even send `FocusIn` events.

**Comment by emanuele6** [comment]
oh, duh. the root window doesn't subscribe to focus events, my bad. I got confused because I didn't understand the issue initally. It actually works.

**Comment by nullchilly** [comment]
Ah sorry, I didn't add steps to reproduce the issue:

- `flameshot gui` while the focus window is chromium
- Press esc
- Right click on chromium and realize you can't

Can confirm it works now, thanks you very much :)
