### ISSUE TITLE
`honor_size_hints` for floating windows only

### ISSUE THREAD

**Issue by musjj** [baskerville/bspwm#1447]
I want to set `honor_size_hints` to `true` for floating windows only. I tried:
```bash
bspc config -n .floating honor_size_hints true
```
But it's not working. Is there a way to do this?

**Comment by emanuele6** [comment]
That is not how `config -n` works: `config` is used to set settings.

Some settings can be set individually for each node (only `border_width` currently).
To set one of those settings on a specific node, you use the `-n` and a node selector that selects that node e.g. `bspc config -n 0x0060102B border_width 10` or `bspc config -n any.local.floating border_width 10` (the first floating window that can be found in the current desktop).

Some settings can be set individually for each desktop (only `window_gap`, and the padding settings currently).
To set one of those settings on a specific desktop, you use the `-d` and a desktop selector that selects that node e.g. `bspc config -d 0x00A00004 window_gap 7` or `bspc config -d 'next.!occupied' left_padding 5` (the first desktop after the focused desktop that is empty).

Some settings can be set individually for each monitor (only the padding settings currently).
To set one of those settings on a specific monitor, you use the `-m` and a monitor selector that selects that node e.g. `bspc config -m 0x00A00002 top_padding 3` or `bspc config -m primary bottom_padding 2` (the primary monitor).

And all settings can be set globally with `bspc config settingname settingvalue` without `-n`/`-d`/`-m`. (and `-n`/`-d`/`-m` are ignored excepted that, like almost any other bspwm command, if one of the specified selectors doesn't match anything, the command fails and does nothing.)

If you set `window_gap` globally, that will be the initial value of newly created desktops; If you set `border_width` globally, that will be the initial value of newly created nodes (except if the node had some atom that told bspwm to not display a border, or the node was added with a `border=off` rule, in which case `border_width` will default to 0).
The padding settings are additive so the effective padding for a desktop is `globalpadding + monitorpadding + desktoppadding`.

`config` can also be used to get the current value of a setting. if you don't use `-n`/`-d`/`-m`, you will get the global value. If you use one of `-n`/`-d`-m`, and the setting can be set individually for that node/desktop/monitor, it output the value of that setting for that specific node/desktop/monitor; otherwise it simply ignores the `-n`/`-d`/`-m` options, and outputs the global value. (except that it doesn't output anything if one of them doesn't match anything.)

---

The problems with your command are that:
1. `.floating` is not a selector, but a modifier, so the command will simply fail and do nothing
   ```bash
   bash-5.1$ bspc config honor_size_hints
   false
   bash-5.1$ bspc config -n .floating honor_size_hints true
   bash-5.1$ printf %s\\n "$?" # 0 means success, non-0 means failure
   1
   bash-5.1$ bspc config honor_size_hints # still false
   false
   ```
   To, for example, update the value of `border_width` for every node that currently exists and is a floating window, you would use the `query -N` command with the `-n` option that, given one or more modifiers, outputs all the nodes that match them, and iterate its output to run `config -n` on every node in it; e.g.:
   ```bash
   bspc query -N -n .floating | while IFS= read -r id; do bspc config -n "$id" border_width 15; done
   ```
2. You are trying to set `honor_size_hints` on a node, even though it is a global setting that can only be set globally.

---

<s>In any case, I don't really understand what your goal is. blabla</s>
What your goal actually is probably is (I only figured it out after writing all the stuff above, please, if you have a problem, ask about that problem directly, don't make people guess what you actually want by saying "bspc config -n .floating honor_size_hints true") to make bspwm only resize windows based on the size hints if the windows are floating (or pseudo tiled).

I think there is currently no way to do that, though this could be fixed quite easily.

There are multiple ways we could change this:
1. Make `honor_size_hints` a node setting, that can be set indivualy on every node, then the user will be able to write a subscribe script to enable `honor_size_hints` resizing when the window becomes tiled:
   ```bash
   #!/bin/bash --
   bspc subscribe node_state | while IFS=' ' read -r _ _ _ id st x _; do
       [[ $st = @(floating|pseudo_tiled) ]] || continue
       if [[ $x = on ]]; then
           then hsh=true
           else hsh=$(bpsc config honor_size_hints) # or hsh=false
       fi
       bspc config -n "$id" honor_size_hints "$hint"
   done
   ```
   It's a bit clunky and hacky, but it is relatively easy to setup and works.

2. Make the `honor_size_hints` setting accept a new value (e.g. "floating") that makes `bspwm` only resizes windows when they are floating or pseudo_tiled. There could also be another new value (e.g. "tiled") that only makes `bspwm` resize nodes if they are tiled.
   This would be more reliable, but it is more limited than the other approach. It would also be a breaking for some users, but, as previously established, we don't care much about that since bspwm is at version 0.x.x.

3. Add the "floating" value for `honor_size_hints`, but also add a new boolean node setting that, if set to `false` disables hints for that node even if the global value for `honor_size_hints` is not `false`.

4. Something else.

Which solution would you prefer?

**Comment by musjj** [comment]
> (I only figured it out after writing all the stuff above, please, if you have a problem, ask about that problem directly, don't make people guess what you actually want by saying "bspc config -n .floating honor_size_hints true") to make bspwm only resize windows based on the size hints if the windows are floating (or pseudo tiled).

Not sure what you're talking about, I've repeated what I wanted to achieve pretty clearly both in the title and in my post. The command is just an example of what I've tried, not my question.

But thanks for the clarification about global vs. node settings. I guess that script is the only way achieve this right now.
I've also realized that `bspc config -n ...` isn't what I want, because it only applies settings to existing nodes, and not for any new nodes that are created after the command is run.

Rather than adding a new value to `honor_size_hints`, I think it's better to add a new option to `bspc rule` instead, since it's more consistent to how scoped configuration is currently handled.

**Comment by emanuele6** [comment]
> Not sure what you're talking about, I've repeated what I wanted to achieve pretty clearly both in the title and in my post.

Well, it was not very clear to me... You said nothing about resizing, and the post just say "I want to set `honor_size_hints` to `true` for floating windows only" which I insist was not very clear. It just sounded like you misunderstood how `config` worked. In any case, let's ignore this.

> Rather than adding a new value to `honor_size_hints`, I think it's better to add a new option to `bspc rule` instead, since it's more consistent to how scoped configuration is currently handled.

I don't think that is a very nice, then there would still be no way to disable hints for an existing node, except by running something like:
```bash
bspc rule -a \* -o "node=$(bspc query -N "$id" -n '@brother' || bspc query -N "$id" -n '@parent')" "desktop=$(bspc query -D -d)" 'honor_hints=off' \
    && xdo hide -- "$id"\
    && xdo show -- "$id"
```
Which I guess is nicer than what you had to do before since you don't have to remove and remember the hints to restore them, you just need to remanage the window again with `honor_hints=on`, but it is definitely not trivial to do.

**Comment by emanuele6** [comment]
I have posted two patches in #1448 that implement my second and third proposed solutions.
