### ISSUE TITLE
Window splitting issue

### ISSUE THREAD

**Issue by astroshift** [baskerville/bspwm#1457]
In the readme, and from previous usage, I know that bspwm normally should tile like this:

```c++
+-----------------------------------+
|                |                  |
|                |        2         |
|                |                  |
|      1         |------------------|
|                |                  |
|                |         3        |
|                |                  |
+-----------------------------------+
```

Instead, I have a problem where the first tile splits vertically twice before it decides to begin a horizontal split. How could this be? Config is completely default, also using a fresh Arch install. Issue example:

```c++
+--------------------------------------------------+
|               |               |                  |
|               |               |        3         |
|               |               |                  |
|      1        |      2        |------------------|
|               |               |                  |
|               |               |         4        |
|               |               |                  |
+--------------------------------------------------+
```

**Comment by ortango** [comment]
[automatic scheme defaults to longest_side](https://github.com/baskerville/bspwm/blob/8fc2269fe0f29a785885bcd9122812eae7226d7b/src/settings.h#L45). if you have an ultrawide monitor you probably have two windows wider then taller before the second split.

**Comment by astroshift** [comment]
@ortango I am using a basic 1080p monitor.

**Comment by emanuele6** [comment]
The default `automatic_scheme` has always `longest_side` since automatic schemes have been configurable, nothing has changed. 385f73e576d4e5fdb09e5f6e77293503e01adf88

`bspwm` splits on the longest side of the focused (insertion) node.
If you have resided the window, the left window, and inserted a window while it was more wide than tall, you will get a vertical split instead of a horizontal split.

If you don't want that and you want to alternate vertical and horizontal splits, simply change the `automatic_scheme` setting to `alternate` instead of `longest_side`:
```
bspc config automatic_scheme alternate
```
That is also the automatic scheme I personally use.

**Comment by astroshift** [comment]
@emanuele6 Thank you very much for the explanation. Not sure how I couldn't find this option in the documentation, but that makes it very clear. I remember it being like this default, but that was before 2018, so that is likely where my confusion comes from. Closing issue as it is now resolved.
