### ISSUE TITLE
bspwm chrome in fullscreen, youtube video also in fullscreen, when exit video fullscreen chrome also exit fullscreen to tiled  

### ISSUE THREAD

**Issue by wutianjun5858** [baskerville/bspwm#1466]
bspwm chrome in fullscreen, youtube video also in fullscreen, when exit video fullscreen chrome also exit fullscreen to tiled;

just chrome triggered this problem, firefox no this problem, but I must use chrome, Can anyone tell me how to solve this problem

**Comment by andro404-MC** [comment]
This seems to be a Chromium issue (probably a feature) and has nothing to do with BSPWM.
I believe this also happened on Windows (I will check to confirm)
f11 to full-screen → video to full-screen → exit video full-screen → Chromium also go back to maximized mod

**Comment by andro404-MC** [comment]
I just tested it in windows, doesn't seem to have the issue
that because I used the built-in key bind (F11 and I don't know of any other way to go to fullscreen other than it) and it using it in BSPWM also doesn't cause the issue.
I am not sure what `bspc node -t fullscreen` does exactly, but basically chromium doesn't have the support of it and doesn't actually go to fullscreen
but still this issue is related to the Chromium side since Firefox support it
You can close this issue
