### ISSUE TITLE
bspc pointer with button 1-3 extremely slow when using fish

### ISSUE THREAD

**Issue by 0X1A** [baskerville/bspwm#197]
I don't know if this is a bug with fish, bspwm or even sxhkd though with the following bindings in sxhkd:
```
super + button{1-3}
	bspc pointer -g {move,resize_side,resize_corner}

super + !button{1-3}
	bspc pointer -t %i %i

super + @button{1-3}
	bspc pointer -u

```
changes are done extremely slowly. I've only had this behaviour happen with fish

**Comment by Stebalien** [comment]
That's because sxhkd will re-execute your shell (which will run the specified command command) for every input event and fish probably has a long startup time. You can start sxhkd with the `-f FREQUENCY` option to reduce motion event frequency but you should really just set a faster shell (I'd just use sh). You can set sxhkd's shell independently using the SXHKD_SHELL environment variable.

**Comment by 0X1A** [comment]
@Stebalien Thanks, setting it to sh solved it.
