### ISSUE TITLE
XCB_CONN_CLOSED_FDPASSING_FAILED’ undeclared 

### ISSUE THREAD

**Issue by madisodr** [baskerville/bspwm#210]
Ubuntu 13.10 / Linux version 3.11.0-26-generic / gcc/g++ version 4.8.1

Getting this error on the most recent pull of code. I installed the required dependencies based on 
[ https://github.com/windelicato/dotfiles/wiki/bspwm-for-dummies ] Must have missed one or two?

Did some digging and found that XCB_CONN_CLOSED_FDPASSING_FAILED is declared in libxcb-sync but installing this didn't fix the issue.

cc -std=c99 -pedantic -Wall -Wextra -I/usr/local/include -D_POSIX_C_SOURCE=200112L -DVERSION=\"0.8.9\" -Os  -c -o bspwm.o bspwm.c
bspwm.c: In function ‘check_connection’:
bspwm.c:375:9: error: ‘XCB_CONN_CLOSED_FDPASSING_FAILED’ undeclared (first use in this function)
    case XCB_CONN_CLOSED_FDPASSING_FAILED:
         ^
bspwm.c:375:9: note: each undeclared identifier is reported only once for each function it appears in
make: *** [bspwm.o] Error 1

**Comment by baskerville** [comment]
I'm not sure how things are packaged on Ubuntu but that constant is in *libxcb* since January 2013.

**Comment by museur** [comment]
"cc -std=c99 -pedantic -Wall -Wextra -I/usr/local/include -D_POSIX_C_SOURCE=200112L -DVERSION=\"0.8.9\" -Os  -c -o bspwm.o bspwm.c
bspwm.c: In function ‘check_connection’:
bspwm.c:372:9: error: ‘XCB_CONN_CLOSED_INVALID_SCREEN’ undeclared (first use in this function)
bspwm.c:372:9: note: each undeclared identifier is reported only once for each function it appears in
bspwm.c:375:9: error: ‘XCB_CONN_CLOSED_FDPASSING_FAILED’ undeclared (first use in this function)
make: *** [bspwm.o] Error 1"

If I by-pass the check:
"cc -o bspwm bspwm.o helpers.o settings.o monitor.o desktop.o tree.o stack.o history.o events.o pointer.o window.o messages.o query.o restore.o rule.o ewmh.o subscribe.o -L/usr/local/lib -s -lm -lxcb -lxcb-icccm -lxcb-ewmh -lxcb-randr -lxcb-xinerama
bspwm.o: In function `main':
bspwm.c:(.text.startup+0x113): undefined reference to `check_connection'
bspwm.c:(.text.startup+0x39c): undefined reference to `check_connection'
collect2: error: ld returned 1 exit status
make: *** [bspwm] Error 1"

In debian lxcb binary, instead of /usr/local/lib:
"/usr/lib/x86_64-linux-gnu/libxcb-icccm.a
/usr/lib/x86_64-linux-gnu/libxcb-icccm.so
/usr/lib/x86_64-linux-gnu/libxcb-icccm.so.4
/usr/lib/x86_64-linux-gnu/libxcb-icccm.so.4.0.0"

etc.

The system has all of libxcb1 plus undependent libxcb-*0.

**Comment by museur** [comment]
Any way to acquire some old version of bspwm?

**Comment by museur** [comment]
Well, I got this fork working just fine. @madisodr pull this: https://github.com/tmathmeyer/bspwm

**Comment by pescek** [comment]
For a workaround, please check my reddit post if that helps.. http://www.reddit.com/r/bspwm/comments/2vsadi/i_am_having_trouble_installing_bspwm_on_debian/coscz6r

**Comment by baskerville** [comment]
Here's a simple *fix*: `git checkout b0e8dd3`.

It would be great to report this problem to the relevant package maintainers though...

**Comment by cryptogranny** [comment]
I've got the same error on Centos 7 with a clone from recent baskerville git.
"git checkout b0e8dd3" - this didn't help much, because it was in "'detached HEAD' state". So this fix is not that simple and helpful. I just cloned from tmathmeyer and it built without any errors.

**Comment by vistamon82** [comment]
any new workaround on this? I'm experiencing the same problem on CentOS 7, but I can't clone the @tmathmeyer git because it doesn't exist any more.

**Comment by Custodia** [comment]
@cryptogranny @vistamon82 

Detached head is nothing nefarious, if you are unfamiliar with git see [this.](https://www.git-tower.com/learn/git/faq/detached-head-when-checkout-commit)

I don't know if the workaround commit is the same for CentOS 7 but for debian wheezy doing the checkout and then making normally works.
