### ISSUE TITLE
bspc window [WINDOW_SEL] --rotate DIR not working(invalid syntax)

### ISSUE THREAD

**Issue by neeasade** [baskerville/bspwm#246]
I might be understanding this wrong. but say I have the 4 windows open like so(with focus on window 1):
1 2 
3 4

And I want to rotate window 1 so that its width is the same as the desktop:
![layout](http://i.imgur.com/8P3wj3B.png)

I would think I would do this with something like `bspc window $(bspc query -W -w) -R right`, where the focused window is 1 in the initial layout. However, when I do this, I get invalid syntax, even though on the man page under window commands there is a -R, --rotate option. 

Might be misunderstanding this - thanks in advance.

**Comment by baskerville** [comment]
Could you provide a schema for the desired result?
The target window is, by default, the focused window, so you can remove the `$(...)` part.
The window version of the rotate command has the following syntax: `-R DIR ANGLE`.
Also `right` is probably not the right direction, because, in your example, there's no splitting edge on the right side of the focused window.

**Comment by neeasade** [comment]
>The window version of the rotate command has the following syntax: -R DIR ANGLE.

I feel silly, that was the part that was not clicking, I was thinking it needed -R (DIR || ANGLE)

What do you mean by schema? the desired end window layout? that's the imgur picture above - the command `bspc window -R right 90` appears to do what I was wanting.

demo: http://a.pomf.se/oehjfl.webm
