### ISSUE TITLE
Add «all» selector.

### ISSUE THREAD

**Issue by eigengrau** [baskerville/bspwm#250]
It would be convenient if the selector syntax, e. g. for desktops, would offer an `all` selector. This could then be used with the query modifiers to yield only empty desktops `bspc query -D -d all.free`. Currently, it doesn’t seem to be possible to have just the modifier without any selector.

**Comment by ikn** [comment]
I would like this too.  Maybe just allow omitting the primary selector (eg. `bspc query -W -w .urgent`)?  Then it becomes clearer that it's a different thing from normal primary selectors.

**Comment by baskerville** [comment]
I'd go with *any*. What would `bspc window any -d any` do?

**Comment by ikn** [comment]
When I first saw this I thought it was asking for 'bspc query' with such a selector to possibly give multiple results.  Reading it properly, there's not much to indicate that, so I probably just assumed since this is something I've been wanting.

To be clear: what I would like is for selectors to 'bspc query' options to allow omitting the primary selector, in which case the call may give multiple results.  If that is the case, you can't specify this special primary selector on its own, without any secondary selectors (since that would just be the empty string), and the behaviour if you could would be the same as not providing a selector - you just get all windows, etc..

Hope that's clear.  Again, this might not be what the issue was meant to be about.

**Comment by baskerville** [comment]
So, this new syntax would only be valid within the context of the *query* command?

**Comment by ikn** [comment]
For my use case, yes.

**Comment by eigengrau** [comment]
I was also primarily thinking of queries. Maybe it would make sense elsewhere, not sure.

**Comment by baskerville** [comment]
Implemented in eb07d2f.
