### ISSUE TITLE
«bspc query -H» sometimes introduces spurious newline

### ISSUE THREAD

**Issue by eigengrau** [baskerville/bspwm#253]
When running `bspc query -H`, a spurious newline sometimes appears in the middle of the monitor description string.

Example below:

```
HDMI-0 emacs 0x0
HDMI-0 I 0x0
HDMI
-0 II 0x0
HDMI-0 I 0x0
HDMI-0 emacs 0x0
HDMI-0 msg 0x2600003
HDMI-0 web 0x2E0008A
```

Calling `bspc query -H` in quick succession shows that maybe 2 out of ten times the command is run, I get a newline in the middle of `HDMI\n-0`. The other times, I do not. Strangely, this always seems to affect the same history entry.

**Comment by eigengrau** [comment]
Occasionally, the newline can be seen in the middle of the WID string as well.

**Comment by rye761** [comment]
I have been unable to reproduce on bspwm 0.9 running on Arch Linux.

**Comment by Stebalien** [comment]
That's because, as far as I can tell, bspc.c:76-93 can read partial lines. This problem usually doesn't manifest because bspwm sends the data line-by-line but the kernel is free to choose how much data it sends at a time. bspc should probably use a buffered file pointer + getline instead of rolling its own implementation. Of course, my diagnosis might be completely wrong :smile:.
