### ISSUE TITLE
rofi -fullscreen does wired stuff with tiled windows layout

### ISSUE THREAD

**Issue by blendi-93** [baskerville/bspwm#319]
for example:

    3 terms open
    +-----------------------+
    |           |           | 
    |           |     2     | 
    |           |           | 
    |     1     |-----------| 
    |     ^     |           | 
    |           |     3     | 
    |           |           | 
    +-----------------------+ 
    
    launch rofi -fullscreen in term 1 
    hit esc (closes rofi)
    
    i get:
    +-----------------------+
    |                       | 
    |           1           | 
    |           ^           | 
    |-----------------------| 
    |           |           | 
    |     2     |     3     | 
    |           |           | 
    +-----------------------+ 

    4 terms open
    +-----------------------+
    |           |           | 
    |     1     |     3     | 
    |     ^     |           | 
    |-----------|-----------| 
    |           |           | 
    |     2     |     4     | 
    |           |           | 
    +-----------------------+ 

    open rofi on term 1
    close rofi

    +-----------------------+
    |     |     |           | 
    |     |     |     3     | 
    |     |     |           | 
    |  1  |  2  |-----------| 
    |  ^  |     |           | 
    |     |     |     4     | 
    |     |     |           | 
    +-----------------------+ 

    open+close rofi again win1 and win2 rotating back

**Comment by reportados123** [comment]
There's a similar problem with fullscreening and then unfullscreening flash videos in Firefox.

1. Open firefox and go to youtube
2. Enable flash video player on youtube instead of html5
3. Open another window such as a terminal
4. Watch a video, fullscreen it (by double clicking the video), and then exit fullscreen.
5. You should see the windows rotate 90 degrees
6. If you fullscreen the window again and then exit fullscreen, the window will rotate back 90 degrees.

This only happens with flash videos in Firefox. I've tested html5 in firefox and this problem does not persist.
