### ISSUE TITLE
Directional movement is non intuitive when moving focus across monitors

### ISSUE THREAD

**Issue by ntrrgc** [baskerville/bspwm#380]
Suppose we have two monitors with two windows each, like this:

    +---------------------+    +---------------------+
    | +-------+ +-------+ |    | +-------+ +-------+ |
    | |       | |       | |    | |       | |       | |
    | |   A*  | |   B   | |    | |   C   | |   D*  | |
    | |       | |       | |    | |       | |       | |
    | +-------+ +-------+ |    | +-------+ +-------+ |
    +---------------------+    +---------------------+
           |   *  |                   |      |
          ----------                 ----------

The stars show what is focused. The focus is at left monitor, window A. Window D is not really focused, but it is the *focused* (default?) window of the right screen, so running `bspc monitor --focus east` will focus D. You can replicate this setup just by opening these four windows and clicking first on D, then on A.

In the case shown in the picture, where we have focused A, we can run this bspc command to focus B.

    bspc node --focus east

It works fine, yet **running it again it will focus D, not C**. That's not very intuitive, since the next window at the right of B is C. bspwm is switching focus just to the monitor at the right, not really the window at the right!

Is this the expected behavior? Is there any way to get a more natural directional movement command that does not jump windows when switching monitors?

**Comment by neeasade** [comment]
This is expected behavior out of the box, as you are switching to the monitor node/recently focused.

some things I tried in this scenario (while focused on `B` in the above picture) that I thought might work but didn't:
- configuring `history_aware_focus` to false (I might not quite understand this conf)
- `bspc node -f east.leaf` (in case just -f east just considered ALL nodes including monitors and thus focused the monitor > last active)
- `bspc node -a east.leaf` (activate the east window node leaf, so that when the monitor node is focused it's the expected node)

**Comment by ntrrgc** [comment]
Since the way bspwm implements this is not satisfactory for me I have ended rolling my own focus utility:

https://github.com/ntrrgc/right-window
