### ISSUE TITLE
Adding balance commands to external rule?

### ISSUE THREAD

**Issue by Chrysostomus** [baskerville/bspwm#393]
Hi!

I created an external rule that always splits automatic windows south (trying to emulate euclid wm). Now, I would like to balance nodes after new window is spawned. I tried adding after the echo command:
  `bspc node @/2 -B`
and
  `bspc node @parent -B`
Neither worked however. Bspwm gets stuck and all commands cease to work. 

Is there a way to add window balancing commands to an external rule?

**Comment by Chrysostomus** [comment]
Here is another script that causes freezing:
```
#!/bin/bash

if [ $(pgrep -cx $0) -gt 2 ] ; then 
	killall $0 && exit 0
else

bspc subscribe node | while read line; do
  bspc node @south -B
  bspc node @north -B
done

fi

```
It seems automating balancing commands is the cause, not specifically using it in external rule. What am I doing wrong?

**Comment by baskerville** [comment]
Thanks, I can reproduce!

The problem comes from the *node_geometry* evens which is emitted via *arrange*: the side effect of `bspc node @south -B` is to produce another call to *arrange* which leads to an infinite communication loop between *bspc* and *bspwm*.

I think I can fix this by being parsimonious regarding the *node_geometry* events.

**Comment by Chrysostomus** [comment]
Thanks!

So it is a bug and will be tried to fix in a update, did I understand correctly?

**Comment by baskerville** [comment]
It is fixed as of b8951ba.

Please note that you can listen to specific events, e.g.: `bspc subscribe node_manage node_stack desktop_layout`.

**Comment by Chrysostomus** [comment]
Thanks. The fix works for the subscriber script, but not for the external rule. Having any balancing command still makes bspwm freeze.

**Comment by baskerville** [comment]
Can you provide the script that causes the freeze?

**Comment by Chrysostomus** [comment]
It is this:
```
#! /bin/sh

fwid=$(bspc query -N -n focused.automatic)
wid=$1
class=$2
instance=$3
title=$(xtitle "$wid")
floats=$(bspc query -T -d | grep -o '"state":"floating"' | wc -l)
if [ -n "$fwid" ] ; then
			echo "split_dir=south"
fi
window-placer $floats $wid
bspc node @/ -B
```
If I comment out balancing, it works

**Comment by baskerville** [comment]
This is a different problem: you're echoing something and *then* you call *bspc* this makes the *read* call in `parse_rule_consequence` block (because it waits for your script to end, but the last call to *bspc* can't return because *bspwm* can't respond while it waits for your script to end).

You need to move the echoing blocks at the end of the script.

I'd also like to add that you should probably do this in a `bspc subscribe node_manage | ...` daemon instead, because, when you balance the current desktop's tree, the new leaf node isn't yet in the tree (remember that one of the possible rule consequences is `manage=off`).

**Comment by Chrysostomus** [comment]
Thanks, makes perfect semse now!

**Comment by baskerville** [comment]
A cleaner way of writing this:
```
floats=$(bspc query -T -d | grep -o '"state":"floating"' | wc -l)
```
would be:
```
floats=$(bspc query -N -n .local.floating | wc -l)
```
