### ISSUE TITLE
About: 'focus_follows_pointer', 'pointer_follows_monitor'

### ISSUE THREAD

**Issue by eva7sk** [baskerville/bspwm#399]
I'm using BSPWM + KDE:
i like set 'focus_follows_pointer true', but it makes KDE's desktop unclickable(KDE has many usefull desktop widget i can't give up), when i set focus_follows_pointer to false i can use all of these widget but focus doesn't follows mouse

set 'pointer_follows_monitor true' can start applications from an empty desktop which is i must set it, 
but when i drag a window from one monitor to another, the mouse cusor jumps to center of monitor which is not smoothly, and in some case like open 'kate' in monitor1, and double click txt file in monitor2, the cursor also jumps to the monitor1

Appreciate your time and effort.

**Comment by Chrysostomus** [comment]
This bug was once fixed, but fixing it caused other more serious issues, so the fix was reverted. This script is designed to work around the issue: https://github.com/Chrysostomus/bspwm-scripts/blob/master/bin/clickpasser
Bind it to your mouse buttons in sxhdrc, like this:
```

# These two are needed if you want to use xfdesktops menus while
# focus_follows_pointer is on
@button3
  clickpasser 3
@button2
  clickpasser 2
```
That doues it for rightclick and middle click, but you can do the same for leftclick too.
