### ISSUE TITLE
Moving windows causes focus to switch with focus_follows_pointer

### ISSUE THREAD

**Issue by Stebalien** [baskerville/bspwm#454]
For example, open up two windows (A(left) and B (right)) side-by-side, put the mouse over window A, run `bspc node -s east`, and observe the focus switch to the window that is now under the cursor (window B).

While this is technically correct, it's really annoying. I expect focus to follow the pointer when, and only when, I'm actually moving the pointer. I know I could also set `pointer_follows_focus` but that would constantly recenter the pointer (I switch windows a lot).

**Comment by neeasade** [comment]
you may be interested in [these bindings](https://github.com/neeasade/dotfiles/blob/master/sxhkd/.config/sxhkd/sxhkdrc#L45-L68). rel post [here](https://github.com/neeasade/neeasade.github.io/blob/source/content/posts/2015-04-28-BSPWM-Multihead.md) ( post was made pre-node, bindings have been updated since then).

**Comment by Stebalien** [comment]
And I thought *my* window moving hotkey was complicated... I did the inverse (disabled/enabled `focus_follows_pointer` before/after swapping the windows) and it works. However, this feels like something that should be done by default.

**Comment by neeasade** [comment]
> However this feels like something that should be done by default
Another open rel issue on this feel: https://github.com/baskerville/bspwm/issues/212

**Comment by Stebalien** [comment]
Nice! You're on a roll.
