### ISSUE TITLE
`bspc query` is buggy

### ISSUE THREAD

**Issue by d125q** [baskerville/bspwm#488]
```sh
% bspc query -D
0x00A00003
0x00A00004
0x00A00005
0x00A00006
0x00A00007
# Exit status 0
```

```sh
% bspc query -D focused
0x00A00003
0x00A00004
0x00A00005
0x00A00006
0x00A00007
# Exit status 0
```

I expect the latter command to give me only the ID of the focused desktop.  Furthermore,

```sh
% bspc query -N
0x00A00016
0x00400078
0x00A0000F
0x0040005E
0x00A0000E
0x00A0000D
0x00400009
0x00400030
0x00400046
0x0140001E
0x01A0011B
0x01600007
# Exit status 0
```

```sh
% bspc query -N .leaf
0x00A00016
0x00400078
0x00A0000F
0x0040005E
0x00A0000E
0x00A0000D
0x00400009
0x00400030
0x00400046
0x0140001E
0x01A0011B
0x01600007
# Exit status 1
```
I expect the latter command to give me the IDs only of leaf nodes and an exit status of 0.  Other commands are similarly buggy.

**Comment by neeasade** [comment]
Your second examples should be `bspc query -D -d focused`, and `bspc query
-N -n .leaf`.

Some notes:

- `bspc query -N -n` implies `bspc query -N -n focused`
- `bspc query -N` returns all node ids -- your `bspc query -N .leaf` exited
1 because .leaf has nothing to apply itself too.
- `bspc query -D focused` in the above should perhaps exit 1 for the same
reasoning as above (cc @baskerville)
- `bspc query -N -n .leaf` would query all nodes that are leafs.


Thanks,
Nathan

**Comment by d125q** [comment]
Thanks.  I wonder why the manpage even mentions selectors to `-N`, `-D`, and `-M`.

**Comment by neeasade** [comment]
> I wonder why the manpage even mentions selectors to -N, -D, and -M.

Actually I had missed that. Hm.

**Comment by neeasade** [comment]
on `bspc query -D focused`, I believe that may be referring to the monitor
(DESKTOP_SEL can be a [MONITOR_SEL:](focused) and MONITOR_SEL can be
focused as well)

So perhaps try `bspc query -D focused:focused`.


Thanks,
Nathan

**Comment by baskerville** [comment]
The new optional arguments for `-{M,D,N}` are references (the default value is *focused*).

For example, `query -N NODE_SEL -n .descendant_of.window` will return the window descendants of `NODE_SEL` and `query -D DESKTOP_SEL -d next.occupied` will return the next occupied desktop after `DESKTOP_SEL`.
