### ISSUE TITLE
How to create type layout icons in bspwm?

### ISSUE THREAD

**Issue by noptx** [baskerville/bspwm#500]
I will make type layout icons like this for bspwm:
![2016-06-06-094027_279x37_scrot](https://cloud.githubusercontent.com/assets/13744901/15810641/dcdc62e2-2bca-11e6-963c-d55be00877e5.png)

This is my code:
Layout() {
	  TILE=$(xdotool key super+t)
	  FLOAT=$(xdotool key super+s)
	  FULL=$(xdotool key super+f)
	  if [[ $TILE ]]; then
		echo -n "%{F#FCFCFC}%{B#363636}  %{F-}%{B-}"
	  elif [[ $FULL ]]; then
		echo -n "%{F#FCFCFC}%{B#363636}  %{F-}%{B-}"
	  else
		echo -n "%{F#FCFCFC}%{B#363636}  %{F-}%{B-}"
	fi
}
after i sh the script nothing change in desktop,but I think to put sxhkdrc script to the that script so that when I press the super + s then look to floating window,super + t to tilling,super + f to fullscreen.
So my question how to add keybinding function in sxhkd to that script?

**Comment by neeasade** [comment]
I'm not sure I understand what you're asking. 

> So my question how to add keybinding function in sxhkd to that script?

You can bind  a script to a keybind in sxhkd like so (assuming it is in your $PATH and executable, and using super + s for example):

```
super + s
    MyScript.sh
```


if you're meaning for this snippet: 

```
TILE=$(xdotool key super+t)
FLOAT=$(xdotool key super+s)
FULL=$(xdotool key super+f)
```

to do actions such as tile/float/full on nodes, I would change the content to be bspc commands instead of keypresses.

**Comment by noptx** [comment]
Thanks.
