### ISSUE TITLE
Desktops are mapped wrong when changing monitors

### ISSUE THREAD

**Issue by poisonby** [baskerville/bspwm#544]
I have this script to switch between my monitor and my TV:

```
#!/bin/bash

output="$(xrandr --listactivemonitors)"

if [[ "${output}" == *"VGA-1"* ]]; then
    xrandr --output HDMI-1 --auto
    xrandr --output VGA-1 --off
else
    xrandr --output VGA-1 --auto
    xrandr --output HDMI-1 --off
fi
```

Usually my keybindings are alt + 1 for desktop 1, alt + 2 for desktop 2, etc. But when I switch monitors, desktop 1 is suddenly mapped to alt + 2, desktop 2 to alt + 3, etc. This persists until I kill bspwm and start X again.

Everything else seems to work correctly, windows are placed on the correct desktops, etc. Maybe there's a better way to do what I want?

Update:

I tried killing/reloading sxhkd, but that didn't work either. The only thing that seems to work is to kill the window manager.

Update:

Using the loop example [here](https://github.com/baskerville/bspwm/tree/master/examples/loop) and then saving the state and reloading bspwm seems to be a workaround.

**Comment by msteen** [comment]
The solution is call `bspc monitor --reset-desktops ...` once the new monitor has been discovered and the old monitor has been removed by `bspwm`, which you can do by subscribing via `bspc subscribe monitor_remove`.

An explanation for your problem is as follows. By default every monitor will get a default desktop assigned named "Desktop". First you add a new monitor (the TV), so this default desktop will be added to it. Then you remove the old monitor, causing its desktops to be appended to the list of desktops on the new monitor (the TV), and thus explains your problem. It causes your list of desktops to become "Desktop", "desktop 1", "desktop 2" and explains why the desktop positioning is off by one. See this [comment and thread](https://github.com/baskerville/bspwm/issues/680#issuecomment-317182944) for more details.
