### ISSUE TITLE
Filter out unwanted unmap notify events

### ISSUE THREAD

**Issue by baskerville** [baskerville/bspwm#618]
We'd like not to unmanage windows after receiving unmap notify events and instead call `set_hidden`…

But in order to be able to do that we need to be able to differentiate legitimate unmap notify events from the ones having been generated by `xcb_destroy_window`.

Our plan is to postpone the processing of unmap notify events.

In addition, we need to set the withdrawn state in `set_hidden_local`, not in `unmanage_window`.

**Comment by msteen** [comment]
Maybe this can help. I found that KDE also had [this problem](https://git.reviewboard.kde.org/r/117422/diff/2-3/). In the case of `xcb_destroy_window` both `XCB_UNMAP_NOTIFY` and `XCB_DESTROY_NOTIFY` are generated, in that order unfortunately, so KDE added a small timer in the case of `XCB_UNMAP_NOTIFY` to wait for a potential `XCB_DESTROY_NOTIFY` to be sent. It seems they [still use this](https://github.com/KDE/kwin/blob/0d8f11405e1aba37ae144ae8a5e7e24cba85cb74/events.cpp#L1418).

The i3 WM seems to either handle this in [their `con_by_window_id` function](https://github.com/i3/i3/blob/8158e4c4155e15ea9442acd960a194376400788b/src/handlers.c#L448) or they [silently handle this somehow](https://github.com/i3/i3/blob/8158e4c4155e15ea9442acd960a194376400788b/src/handlers.c#L480) (the window not being there anymore).

I wonder how awesome WM works around this issue. Looking at [their source code](https://github.com/awesomeWM/awesome/blob/27c3b96a08139d92ccdd22886cfb04bf54c18512/event.c) it seems like they would also generate bad window messages. They directly pass the unmap event to the unmap handler which assumes the window is valid (the second parameter to `client_getbywin`), so if 
`XCB_UNMAP_NOTIFY` is also generated for `xcb_destroy_window` you would think they also run into this problem.

**Comment by baskerville** [comment]
Thanks, I think the best approach would be to simply ignore a few errors (see *dwm*'s `xerror` function).

**Comment by msteen** [comment]
I would generally prefer treating the cause and not the effects, due to the potential other side effects of the cause and the potential side effects of fixing the effects (e.g. in this case, ignoring errors that should not be), so my preference would be to try the approach of KDE first. On the other hand if the KDE approach would involve potential timing issues, I would prefer the solution that consistently works, even if it only solves the effects. I would expect `xcb_destroy_window` to direcly invoke `unmap` before `destroy` and considering KDE still has that code, I would find unlikely that it would still cause problems, but obviously this decision is up to you.
