### ISSUE TITLE
Focus issues

### ISSUE THREAD

**Issue by moviuro** [baskerville/bspwm#625]
Hi,

Weird behavior that I have been experimenting since August (installation date) with bspwm:

* I open 2 applications (urxvt, mpv, google-chrome, chromium, a combination thereof); they are both open next to each other;
* I focus one, do stuff (write, select with mouse, whatever);
* I try to focus the other on with the mouse (hover): **fail**. hmmm. *OK, I'll use the keyboard!*
* Focus second window with keyboard (`Meta` + `arrow`);
* Typing works (**yay**)

And now the most fun and illogical part:

* clicking on the focused window causes the click to be sent inside the previous (now unfocused) application, at its border (*I guess!?*).
* Invoking the lockscreen **fails** (https://github.com/i3/i3lock/blob/d2130092cf588c02d7a0e74c0de85dc261b6823b/xcb.c#L244 < this is the error)

However, there is a "fix":

* Change desktop/workspace
* Doing things afterwards *might* make the bug appear again, though.

This behavior shortly disappeared during the last two weeks, but it's back in action: :sob:. So now, i don't know where to look, nor which info might help. (Behavior has been recorded here: https://my.mixtape.moe/ktzyvz.ogv; first part is trying to resize, then just hovering the window breaks, then clicks get misdirected)

* intel i5 6600K (integrated graphics)
* RAT7 mouse (Madcatz) (I have no other mouse)
* I use `startx`

Ideas?...

The issue also happened when I was using i3 + sxhkd.

**Comment by msteen** [comment]
A quick google shows me that it is not the easiest mouse to get to work properly on Linux and that its interaction with the X server can cause it to misbehave, so it most definitely seems to be related to your mouse, especially since the problem occurs when using the mouse and in multiple window managers. Did you check the [Arch Linux wiki entry](https://wiki.archlinux.org/index.php/Mad_Catz_Mouse) on it? It also refers to [an in-depth blog post](https://delightlylinux.wordpress.com/2013/07/29/using-the-mad-catz-m-m-o-7-with-linux-mint-and-ubuntu/) about setting up your mouse properly under Linux. Good luck!

**Comment by moviuro** [comment]
Indeed, the problem is related to my hardware. I'll be closing the issue then, thanks :wink:
