### ISSUE TITLE
understanding the switch desktops option

### ISSUE THREAD

**Issue by ninrod** [baskerville/bspwm#685]
hi, @baskerville and thanks for the program.

I have this setting working as of `pacman -Syu` 2017.07.29:

```sh
# -------------------------- focus/swap --------------------------
alt + {1,2,3,4,5,6,7,8,9,0}
  bspc desktop -f {I,II,III,IV,V,VI,VII,VIII,IX,X}

ctrl + {1,2,3,4,5,6,7,8,9,0}
  bspc desktop -f {I,II,III,IV,V,VI,VII,VIII,IX,X}

# focus or send to the given desktop
super + shift {1-9,0}
	bspc node -d '^{1-9,10}'

```

I wonder why I cannot set my 2 first bindings to use the `1-9,0` notation?

**Comment by neeasade** [comment]
missing a +: super + shift + {1-9,0}

**Comment by msteen** [comment]
Do you mean the following does not work for you?

    alt + {1-9,0}
      bspc desktop -f {I,II,III,IV,V,VI,VII,VIII,IX,X}

I just tried this in my config for my desktop names and it works fine. Besides the missing `+` as @neeasade noticed you are also using focus (`-f`) for your swap (`-s`) case. To make it stand out more and prevent me from having to check the manual (if they are less obvious then these are) I tend to just use the full names (`--focus` / `--swap`). You can also combine you rules like this (should work, I've tested them with my desktop names):

    {alt,ctrl,super + shift} + {1-9,0}
      { bspc desktop --focus \
      , bspc desktop --swap \
      , bspc node --to-desktop \
      } {I,II,III,IV,V,VI,VII,VIII,IX,X}

If these are not working for you, there might have been a regression since version 0.5.6, which is the version I am using.

**Comment by baskerville** [comment]
@msteen Are you using *0.5.6* because you need a particular feature that's missing from the latest version?

**Comment by msteen** [comment]
@baskerville Not at all, it just happens to be the version supplied by the package manager I am using. The only reason I mentioned my version was because it was the only thing I could think of that could describe why it was not working for the issue author while it worked fine for me, if it was not one of those typo's, but I doubt this is the case. Just being thorough.
