### ISSUE TITLE
Switch to a desktop using <desktop_name>.local

### ISSUE THREAD

**Issue by Tezkerek** [baskerville/bspwm#698]
I have a weird issue, I have two monitors like this:
`bspc desktop HDMI-1 -d 1 2 3 4 5 6 7 8 9`
`bspc desktop eDP-1 -d 1 2 3 4 5 6 7 8 9`

And I am trying to switch to the desktop named `2` belonging to the focused monitor:
`bspc desktop -f 2.local`

This works on my HDMI-1 monitor, but gives exit code 1 when running on the eDP-1 monitor.
Using `bspc desktop -f ^11` works, but I want to focus the desktop using its name.

**Comment by msteen** [comment]
Unless I am misunderstanding the code, it does seem to be the case that `bspwm` will only [return the first desktop matching the name](https://github.com/baskerville/bspwm/blob/0a9b6153afccbc996777d12bb6b3993cacb41542/src/query.c#L790). I just tried to reproduce this issue:

    bspc monitor ^1 -a 2
    bspc monitor ^2 -a 2

And indeed `bspc desktop -f 2.local` on monitor `^1` shows me desktop `2`, while on monitor `^2` I get an error code of 1, which makes sense if you consider the result of `bspc query -D -d 2`. It will only show the desktop id of the desktop first matching the name. This will hold for any situation where the desktop name is queried, not just in a multiple monitor setting:

    bspc monitor ^1 -a 2
    bspc monitor ^1 -a 2

And while on the first desktop named `2` run `bspc desktop -f '2.!focused'`, which will fail as well, while on the second desktop named `2`, it will work. Again, this is because it will only consider the first desktop matching the name, so the filters will apply on to that single desktop.

The reasoning why only a single desktop is returned when using a desktop name is likely because you would only want to apply the desktop actions on a single desktop, but this does not explain why this is not enforced after filtering or why this is also the case when querying a desktop name where returning multiple id's are not problematic, so unless I am missing something this indeed seems like a bug.

The two workarounds I can think of right now are create a function that checks the currently focused monitor and changes `2` in `^11` if it is on you second monitor. Maybe using `bspc query --names -M -m`. Or you could just use unique names, and if you do not use them for displaying, you could do something like `bspc desktop -f $(bspc query --names -M -m)2` if you have all you names desktop names prefixed with the monitor name.

**Comment by baskerville** [comment]
The index is relative to the selected monitor when a monitor prefix is given:
```sh
bspc desktop -f focused:^2
```

**Comment by msteen** [comment]
In this case where the desktop names match up with the indexes, that solution works out fine. If the desktop names are different you could use this:

    mon_sel='^2'
    desk_name='2'
    bspc desktop "$mon_sel":^$(bspc query --names -D -m "$mon_sel" | sed -n "/^${desk_name}$/=" | head -n1) -f

Or more generally, if you just want the desktop ids matching a certain desktop name within a certain monitor:

    mon_sel='^2'
    desk_name='2'
    paste \
      <(bspc query -D -m "$mon_sel") \
      <(bspc query --names -D -m "$mon_sel") \
      | grep $'\t'"$desk_name"$ | cut -f1
