### ISSUE TITLE
Can't focus to floating window with the keys super + (h,j,k,l), and unhappy about the new keep focus

### ISSUE THREAD

**Issue by Alkeryn** [baskerville/bspwm#721]
Well before the upate i could focus to a floating window with the keys super + (h,j,k,l)
Now i just cant and have to do super + c to cycle until i'm on the floating one

Also a new "feature" that bugs me since the new version : 
if i send a focused node to another desktop, it keeps me focused on this node and change the focused desktop
which annoys me since now i can't send a window to another desktop while staying on current desktop

Plus this new feature isn't usefull since you could just add bspc desktop -f after the command in sxhkdrc for the same effect

so forcing staying focused isn't really unix like since there now isn't a good way to send a node to another desktop while staying on the current one

But yeah it is your code, your choice, that's just my opinion ^^

**Comment by msteen** [comment]
Not sure about the floating windows, since I only use them for popups that live shortly, but I do now about the focus should follow by default argument, since I proposed it.

What the default behavior should be for moving a focused node to another desktop is not clear cut, arguments could be made in favor of both behaviors. From the perspective of a user (often a single simple `bspc` call / script containing it), I would find following the focused node to be more intuitive, but from the perspective of a script (automating some more complex behavior), I would find *not* following the focused node more intuitive.

So you could argue my feature request has been implemented too broadly, but @Alkeryn wouldn't you agree that the current situation is a clear improvement for e.g. swapping desktops, which now behaves similarly to swapping nodes and follows the focused desktop? Or do you also have arguments in favor of the old behavior for that?

> Plus this new feature isn't usefull since you could just add bspc desktop -f after the command in sxhkdrc for the same effect
> so forcing staying focused isn't really unix like since there now isn't a good way to send a node to another desktop while staying on the current one

You can still reproduce the old behavior by having e.g. the following in your `sxhkdrc`:

```
super + alt + {1-9,0}
  bspc node --to-desktop {1st,2nd,3rd,main,files,apps,terms,conf,webapps,media} && \
  bspc desktop --focus last
```

So @Alkeryn I do agree that the follow focus feature might have been applied to broadly, but if you find the feature as a whole a mistake, I have to disagree, because I do not see why the new behavior for e.g. swapping desktops is worse than the old behavior.

I think the best solution would be some change in the CLI that would allow you to choose between the behaviors, because there are clear downsides to having to resort to fix commands (appending `--focus` or `&& bspc desktop --focus last`):
1. These fix commands might not be obvious to users that are not that familiar with the CLI of `bspc`.
1. It introduces notable lag. You can actually see the focus being fixed.

But this is indeed up to @baskerville to decide.

**Comment by baskerville** [comment]
The node selector doesn't have to be the focused node: `bspc node -f last.local && bspc node last.local -d DESTINATION`.

**Comment by msteen** [comment]
@baskerville Wouldn't `bspc node -f last.local` fail for the last node?

**Comment by Alkeryn** [comment]
@baskerville The issue is this case scenario
Before :
I have chrome opened on desk 1
i send chrome to desktop 2 and have an empty desktop
now i just open my terminal

Now : 
After sending chrome to desk 2, i'm on desk 2, and i can't focus to last node (on desk 1) since there isn't a node on desk 1 to begin with

Still this is a good feature but i already added that myself with sxhkd 
but now it just broke my "send to desktop without focus"

and as for focusing to a floating windows with {hjkll} i still didn't found a way ^^"

**Comment by msteen** [comment]
@Alkeryn Why not do what I proposed? Instead of focusing the node, focus the desktop back. And with regards to your {hjkl} focus issues with floating windows. I have been using this:
```
super + {h,j,k,l}
  d={west,south,north,east}; \
  bspc node --focus $d || \
  bspc monitor --focus $d
```
Which works just fine on the latest git version. I just checked it with floating windows, and could not reproduce it. What commands are you using? That my version works does not rule out there might a bug with another approach that ought to work, but somehow no longer does.

**Comment by Alkeryn** [comment]
Well i have this in my sxhkd

# focus the node in the given direction
super + {_,shift + }{j,k,i,l}
        bspc node -{f,s} {west,south,north,east}

Before update it could focus to floating nodes
now it just focus to tilled ones like if floating where on another scope of focus or something
and it does it on my 2 compters ^^"

**Comment by msteen** [comment]
@Alkeryn I can get it to focus between floating nodes and towards a tiled node that is underneath it, but not from the tiled node underneath back to the floating nodes. Was that last thing possible to do in older versions? If that is not it, what exactly do you mean with "focus to floating nodes"?

**Comment by Alkeryn** [comment]
Exactly in previous versions you could focus from a tilled node underneath back to a floating node

That's the issue i'm reporting
now i have to cycles through all nodes until i'm on the floating one which is quite anoying ^^

**Comment by baskerville** [comment]
The solution to the first rant, which has to do with 7561be4, is:
```
bspc config directional_focus_tightness low
```

The solution to the second rant, which has to do with 412da35, is:
```
bspc node -g hidden -d DESTINATION -g hidden
```
