### ISSUE TITLE
Reset monocle mode after last window closed

### ISSUE THREAD

**Issue by Jumblemuddle** [baskerville/bspwm#814]
I've been trying to implement a way to reset monocle mode after all windows in a desktop have been closed, but I can't seem to find a way to do it without modifying the source.

If someone can implement this feature, great, otherwise, I'll try to implement it and create a PR when I have more time.

**Comment by yrkv** [comment]
I just made this because it seemed like a nice feature. I'm a bit of a beginner with this kind of stuff but I think it works as expected. Just stick this in ~/.bin or something, and call it (with &)  in your bspwmrc. There are probably better ways to do this than this script.

`
#!/bin/zsh

bspc subscribe | while read line; do
    DESK="$(echo $line | grep -Eo 'F[^:]+' | cut -c2- )"
    if [ "$DESK" != "" ]; then
        bspc desktop "$DESK" --layout tiled
    fi
done
`

**Comment by Jumblemuddle** [comment]
That's quite nifty, thanks @yrkv!
I should spend some more time fully understanding bspc's subscribe syntax.
