### ISSUE TITLE
Inconsistent symmetrical resizing

### ISSUE THREAD

**Issue by sudo-nice** [baskerville/bspwm#902]
Let's open three terminal windows and balance them like this:

```
+---------------+---------------+---------------+
|               |               |               |
|               |               |               |
|               |               |               |
|               |               |               |
|               |               |               |
|       L       |  Active node  |       R       |
|               |               |               |
|               |               |               |
|               |               |               |
|               |               |               |
|               |               |               |
|               |               |               |
+---------------+---------------+---------------+
```

Now, let's try to expand the center node symmetrically:
`bspc node -z right 60 0 -z left -60 0`

I expect the nodes `L` and `R` to keep being equal in size, but the sizes differ.

**Comment by baskerville** [comment]
Indeed.

That's an interesting problem: if the active node and *R* share the same parent, then moving the separator between *L* and the active node will change the size of *R*'s parent and therefore the size of both *R* and the active node.

What we want instead is to adjust the split ratio between the active node and *R* so that the width of *R* stays constant.

**Comment by sudo-nice** [comment]
Thank you!
