### ISSUE TITLE
[Question/Feature request] More layouts, similar to awesomeWM

### ISSUE THREAD

**Issue by lukasbash** [baskerville/bspwm#913]
Do you think it makes sense to add more layouts that are available out of the box?
I know, for most of the people `Spiral`, `Alternate` & `Longest side` are enough as tiling schemes but could you think of an API or similar to implement more schemes?

**Comment by baskerville** [comment]
The only *layouts* that bspwm provides are *tiled* and *monocle*. What you're referring to are different ways of inserting a new window. bspwm is unusual because it only deals with frames. Some window managers have layouts but no frames (*DWM*) and some have both frames and layouts (*herbstluftwm*).
